### ISSUE TITLE
Motion sensing not functioning

### ISSUE THREAD

**Issue by openhab-5iver** [vbier/habpanelviewer#1]
Providing log from discussion [here](https://community.openhab.org/t/habpanelviewer/34112/18). There are a few oddities in this log.

[log.txt](https://github.com/vbier/habpanelviewer/files/1351464/log.txt)

**Comment by vbier** [comment]
Thats lot of information. Interesting seems to be:
`09-25 14:33:30.157  3682  3682 D Camera  : app passed NULL surface`

I have changed the way the surface is passed to the camera. Can you please check if this works?
I attached the new apk below, please change the extension as it is not allowed to attach apks.

![app-debug apk](https://user-images.githubusercontent.com/22752389/30860992-9dcc5194-a2c9-11e7-82ec-52bc0291510a.png)

**Comment by openhab-5iver** [comment]
The first time I go into Status Info, there are stats for the camera. Exit Status Info, wait, then check Status Info again, no stats. If I start the app and don't check the Status Info, the screen still does not  will go off and turns on with motion. The Camera API 2 does not find a camera. With both of them, and other builds, the tablet seems to get a bit warm. I will try to get some logs later tonight.

**Comment by vbier** [comment]
To make it a little easier for you, I have added a preference to switch between the old and the new API so you dont't have to reinstall that often. A restart of the app has to be done manually when changing the preference. I also fixed a problem in the new API code and added more logging.

![app-debug apk](https://user-images.githubusercontent.com/22752389/30898754-25c4e76c-a35d-11e7-9008-47cde606bda3.png)

**Comment by vbier** [comment]
One more update. I tested this with my old nexus 5 with lineage 7.1.2 and had to change two more things in the code in order to get motion detection working. I am a little bit confused why different devices behave different with the same code, as the restart also does not work with the nexus 5. I will have to investigate this, but I am not going to have much time during the next week.

This is the version that works on my Galaxy Tab A as well as on the Nexus 5:
![app-debug apk](https://user-images.githubusercontent.com/22752389/30957974-0119a59e-a43c-11e7-8fa7-efefa284c32c.png)

**Comment by openhab-5iver** [comment]
Sorry, I haven't had time to test more, but I _should_ have some time later today. I will check out the latest version. And thank you!

**Comment by vbier** [comment]
does it work now? or do you have a new log?

**Comment by openhab-5iver** [comment]
Unfortunately, no. Neither API turns the screen off or on with motion. The same error occurs when motion starts or 1 minute after it stops, and it is the same when either API is selected. But in looking at the logs from when the API is changed, I question whether it is actually ever using the v2.

[v0.9.txt](https://github.com/vbier/habpanelviewer/files/1351450/v0.9.txt)

**Comment by openhab-5iver** [comment]
After testing, logging, and writing this up, I turned to my tablet and the screen was off! Luckily, I was still logging. I'll do some more testing...

**Comment by vbier** [comment]
Looking at you first log (v0.9.txt) everything looks as it should, motion detection is running (v2), it captures an image and processes it every 0.5 seconds. No errors or anything else, but no motion is detected.

In the second log I can not see any usage of the v1 api. It only uses v2. Did you restart the application after changing the preference?
Can you please attach a complete log (containing the application start) of a run with old api enabled? So enable old api, restart, wave your hand in front of the camera and capture the log.

As to the temperature, I did not notice that with any of my devices. Detection only needs 0.015 seconds per frame, and only 2 frames per second are analyzed. This should not be too much for the CPU.

**Comment by vbier** [comment]
If you still have problems, reopen and add more information.
