### ISSUE TITLE
Hide title bar

### ISSUE THREAD

**Issue by s-simma** [vbier/habpanelviewer#11]
I have installed the new version 0.9.14.
Everything works so far as expected.
But what i'm missing is the Option: "Hide title bar"

Would it be possible to bring it back (at least if on specific url/dashboard is spezified)? I would be very thankfull.

Thank's for this great app.

**Comment by vbier** [comment]
Go to start page, open context menu, select go to url, add &kiosk=on to the
URL. Set page as new start page.

Am 10.02.2018 15:07 schrieb "s-simma" <notifications@github.com>:

**Comment by s-simma** [comment]
Thank you very much.
Works great.
But you have to add ?&kiosk=on to the start url (not &kiosk=on).
