### ISSUE TITLE
Prevent longpress context menue

### ISSUE THREAD

**Issue by s-simma** [vbier/habpanelviewer#12]
Hi,
Switching on kios mode with **?&kiosk**=on works great to hide title line.

But would it be also possible to prevent  "Long-Press" to show the following selection (if kiosk is on)
The same is with Long-Press on the HOME button (opens browser)

**Comment by vbier** [comment]
Please create issues for questions or feature requests. Use the forum for this. Create issues if there are bugs in the app only.
