### ISSUE TITLE
Habpanel viewer Does not display Image Of Camera Feed widget

### ISSUE THREAD

**Issue by Julianex22** [vbier/habpanelviewer#24]
I have configured in my sitemap my camera Dahua IPC K35 , on the Video element,

Video item=Camara1 icon="camara" url="http://admin:7121799422@192.168.10.108/axis-cgi/mjpg/video.cgi/" encoding="mjpeg"

It works very fine in Openhab App for android movil but on Habpanel Viewer Widget Camera Feed does not show the video (I have put the same URL)
.In habpanel when i modified via PC it show the video correctly.
Habviewer Version 0.9.22
Installed on Android 8.1

Could someone help me about???

Thanks

**Comment by vbier** [comment]
Does it work when you open the HabPanel page with Chrome on the modile device?
Do you know if there is some public mjpeg stream i can use to test?

**Comment by Julianex22** [comment]
Hello vbier.
 Yes on Chrome neither the widget show the video, I`ve been look around to find some solution to this trouble, but really I dont Know where to start.
Do you Know some way to avoid this feature????

Thanks

**Comment by vbier** [comment]
Closing this as there is nothing I can do.
