### ISSUE TITLE
Cannot use the app on lineage15.1 sony xperia Tablet Z

### ISSUE THREAD

**Issue by I-am-stefan** [vbier/habpanelviewer#25]
## Expected Behavior

I can scroll through the start wizard and start editing my configurations

## Current Behavior

After the fifth screen (big key is shown) the next scroll will allways terminate the app. I can see for one second the database symbol but meanwhile the APP crashed dialog is shown.

## Steps to Reproduce (for Bugs)

1. Start the app
2. Scroll a little bit in the wizard  

## Your Environment

1. Use the sony xperia Tablet Z 
2. Use the lineageOS 15.1-20181126 unofficial image
3. Install the app from f-droid

**Comment by vbier** [comment]
Can you please generate an adb Log?

**Comment by I-am-stefan** [comment]
of course. Do you know a good tutorial to do so? I do not generate a adb log ever, is it easy?

**Comment by I-am-stefan** [comment]
Sorry, I use the wrong button

**Comment by I-am-stefan** [comment]
ok, its done. How can I send the log to you? I am not able to analyse the log, so I cannot estimate if there are some information inside the log, that are unsecure to post it here directly...

**Comment by vbier** [comment]
You can zip it and send it with e-mail to HABPanelViewer@bayshore-networks.com.

**Comment by vbier** [comment]
Can you test if this apk works? 
  https://github.com/vbier/habpanelviewer/raw/master/app-debug.apk
Looks like i have already accidentally fixed the problem.

**Comment by I-am-stefan** [comment]
It works like a charm, thanks. 

When do you deploy this version to f-droid?

**Comment by vbier** [comment]
I am currently looking into another problem. I plan to release when this is fixed.
