### ISSUE TITLE
Unable to setup app. Won't detect Server neither allow manual config

### ISSUE THREAD

**Issue by Chanete** [vbier/habpanelviewer#27]
HI, I'm trying to install the app in a Huawei P20. The app starts the setup wizard showing the use cases but, when it gets to detect my OH server, it doesn't detect it (is running in a Raspi) . I check the radio button telling that I will set it up manually, the wizard ends, but  start over again. 

After going a couple times through this behavior it ends up with a screen with big letters that states: "Configuration missing, Neither the  openHab server URL not a start page has not been defined in the settings.. Please specify them in the application settings"  but there is no way to get to the settings tab, there is nothing I can do in this screen. 

Is there any way to cancel the setup wizard and do it manually??

Thx in advance 
Chano

**Comment by vbier** [comment]
One of the intro pages says:
> You can configure HPV by opening the menu and selecting Preferences. To open the menu, swipe with your finger from the right side of the screen to the middle.
Have you tried that after the intro completed?

I will see if I can reproduce the restarting intro.

**Comment by Chanete** [comment]
Perfect! Swiping left I was able to configure the app!!

I think it's a good idea to put that message in the screen.
THX!!!
