### ISSUE TITLE
Enable HTML 5 video autoplay

### ISSUE THREAD

**Issue by sidamos** [vbier/habpanelviewer#28]
I was excited to see that HTML 5 video is working if I enable hardware acceleration! :-)

Could you please also enable autoplay? Should be possible with:
webView.getSettings().setMediaPlaybackRequiresUserGesture(false);

Thanks!

**Comment by vbier** [comment]
I have added a setting for allowing auto-play of videos in web pages. But note that this does not trigger auto-play, this has to be done by the web page itself.

**Comment by sidamos** [comment]
Pity, although the Nest Camera URL ends with ?autoplay=1, it still does not autoplay.

**Comment by vbier** [comment]
I have tested it with this page https://www.w3schools.com/tags/att_video_autoplay.asp and the video does start to play automatically. But when investigating this, I saw lots of posts from people complaining that this does not help. They had to embed some javascript in onLoad that started the video element in the page.
