### ISSUE TITLE
KEEP_SCREEN_ON does not work on some devices when received while in standby

### ISSUE THREAD

**Issue by vbier** [vbier/habpanelviewer#29]
KEEP_SCREEN_ON should wake up the device and make sure it does not go to sleep any more while HPV is active. On some devices, the command does wake up the device, but does not force it to stay on. It keeps the device awake when the command is received while active, though.

**Comment by vbier** [comment]
This is a test version with increased logging:
https://github.com/vbier/habpanelviewer/raw/keepScreenOnOreo/app-debug.apk

**Comment by wiinf** [comment]
here are the log file from the test-version: 
[adb_debug.zip](https://github.com/vbier/habpanelviewer/files/2734233/adb_debug.zip)

Thank you!

**Comment by vbier** [comment]
Looking at the log these are the relevant lines:

> 01-07 21:29:52.946   524   866 I PowerManagerService: Waking up from sleep (uid=10083 reason=HPV:ScreenOnWakeLock)...
> 01-07 21:29:52.958   524   550 I DisplayPowerController: Blocking screen on until initial contents have been drawn.
> 01-07 21:29:52.977   524   550 V WindowManager: Set focused app to: AppWindowToken{94af571 token=Token{b8c8a01 ActivityRecord{65203e8 u0 de.vier_bier.habpanelviewer/.MainActivity t74}}} old focus=AppWindowToken{94af571 token=Token{b8c8a01 ActivityRecord{65203e8 u0 de.vier_bier.habpanelviewer/.MainActivity t74}}} moveFocusNow=true
> 01-07 21:29:52.979  1657  1915 D HPV-ScreenControllingAc: sending keepOn intent: true
> 01-07 21:29:52.983   253   269 I vendor.mediatek.hardware.power@1.1-impl: notifyAppState pack:de.vier_bier.habpanelviewer, act:de.vier_bier.habpanelviewer.MainActivity, pid:1657, state:1
> 01-07 21:29:53.003   524   550 V WindowManager: findFocusedWindow: Found new focus @ Window{5306d1d u0 de.vier_bier.habpanelviewer/de.vier_bier.habpanelviewer.MainActivity}
> 01-07 21:29:53.004   524   550 V WindowManager: findFocusedWindow: Found new focus @ Window{5306d1d u0 de.vier_bier.habpanelviewer/de.vier_bier.habpanelviewer.MainActivity}
> 01-07 21:29:53.029  1657  1657 D HPV-ScreenControllingAc: registered receiver
> 01-07 21:29:53.029  1657  1657 D HPV-ScreenControllingAc: window=com.android.internal.policy.PhoneWindow@458b5d3
> 01-07 21:29:53.029  1657  1657 D HPV-ScreenControllingAc: onStart: set keep on: true
> 01-07 21:29:53.030  1657  1657 D HPV-ScreenControllingAc: window=com.android.internal.policy.PhoneWindow@458b5d3
> 01-07 21:29:53.038   524   545 I DisplayManagerService: Display device changed state: "Integrierter Bildschirm", ON

Judging from the log, everything looks like it should. The tablet wakes up, the activity is started and it sets the window flag to keep the screen on.

This is the log of my Oreo device, it shows only little difference to your log:
> 2019-01-08 14:23:33.014 660-3398 I/PowerManagerService: Waking up from dozing (uid=10081 reason=HPV:ScreenOnWakeLock)...
> 2019-01-08 14:23:33.019 660-692 I/DisplayPowerController: Blocking screen on until initial contents have been drawn.
> 2019-01-08 14:23:33.029 660-686 I/DisplayManagerService: Display device changed state: "Integrierter Bildschirm", ON
> 2019-01-08 14:23:33.033 223-223 D/SurfaceFlinger: Set power mode=2, type=0 flinger=0xb3a4e000
> 2019-01-08 14:23:33.033 223-223 D/qdhwcomposer: hwc_blank: Unblanking display: 0
> 2019-01-08 14:23:33.036 13300-13435 D/HPV-ScreenControllingAc: sending keepOn intent: true
> 2019-01-08 14:23:33.237 13300-13300 D/HPV-ScreenControllingAc: registered receiver
> 2019-01-08 14:23:33.237 13300-13300 D/HPV-ScreenControllingAc: window=com.android.internal.policy.PhoneWindow@9bff0b1
> 2019-01-08 14:23:33.237 13300-13300 D/HPV-ScreenControllingAc: onStart: set keep on: true
> 2019-01-08 14:23:33.238 13300-13300 D/HPV-ScreenControllingAc: window=com.android.internal.policy.PhoneWindow@9bff0b1
> 2019-01-08 14:23:33.240 13300-13300 D/HPV-ScreenControllingAc: onStart: set brightness: -1.0

I have no idea why this does not work for you. I will add a delay between turning on the device and setting the window flag. This is a rather desperate attempt, but it might help.

**Comment by vbier** [comment]
I have now updated the apk once more. It contains a 2 second sleep before setting the flag to keep the screen on. Can you check if this makes a difference?

**Comment by wiinf** [comment]
Now, it works! Thank you! 

Because it seems to be more a bug from the Trekstor Tab, it seems to be better to send a second command from openhab(SCREEN_ON; SLEEP 2 seconds,  KEEP_SCREEN_ON). I tested this with the Playstore Version and it work also. That makes a code change unnecessary. What do you think about that?

**Comment by vbier** [comment]
Sounds good to me.

I have integrated the minor changes into the main branch and enhanced the command description in the help file.
