### ISSUE TITLE
motion detection does not work when SCREEN_DIM has been sent

### ISSUE THREAD

**Issue by vbier** [vbier/habpanelviewer#30]
SCREEN_DIM starts the EmptyActivity, leading to the destruction of the TextureView for the preview. This stops the camera and effectively disables motion detection.

**Comment by vbier** [comment]
Destroying the TextureView also breaks CAPTURE_CAMERA.

**Comment by BoBiene** [comment]
Hi  @vbier,

seems still not to work. When i start the application, the Camera image is fine. Now i can see the blocks when motion is detected and the message "motion".

But when i go to the settings and return back OR I dim the screen and resume (via touch on the screen) i get a message "front camera not found". 

Without preview get the "front camera not found" too.

**Comment by vbier** [comment]
Too bad, this works on both of my devices. Can you generate another log, please?

**Comment by BoBiene** [comment]
Shure, no problem: https://pastebin.com/AUwsUVa8

**Comment by vbier** [comment]
I have trouble reproducing this. I made another change and updated the apk. Does that make a difference?

What device do you test this on and which version of Android is it running? Does it make a difference if you enable/disable HW acceleration in the preferences?

**Comment by BoBiene** [comment]
@vbier,

Thank you! i'ts working now for me on my FireTab 👍 :)

**Comment by vbier** [comment]
That's great. Can you please generate another log where you send SCREEN_DIM and wake up the tablet twice?

**Comment by vbier** [comment]
I can see that the screen turned on due to motion, but I can not see SCREEN_DIM. This looks different from the logs you posted in the past. It looks like this should have worked all the time, even before my changes.
