### ISSUE TITLE
High CPU usage on OH Server

### ISSUE THREAD

**Issue by Hobohome** [vbier/habpanelviewer#32]
Issue - HPV seems to cause high CPU consumption on OpenHab Server.
I am using a Asus 7" Zenpad to display HabPanel. 
When I launch chrome on the tablet and connect to Habpanel/Openhab (running on a Raspberry PI 3B+) the CPU consumption on the PI goes from an average of 16% to around 22%.
When I then kill the browser connection to the PI and then launch HPV to make the same connection, the PI CPU consumption immediately jumps to 50% - 60% and sometimes hits 80%. This high CPU consumption continues - then stops as soon as I terminate HPV.

Is this because HPV is interacting with HP Server on the PI more frequently than a standard browser?
Is this expected behaviour? 

This may be unrelated, but I mention it for completeness... The HPV menu shows "Not Connected" instead of the server URL. The values all seem to update - but I can not get the tablet to respond to the OH command item. I have been through the troubleshooting guide and checked everything I can, but the menu still shows "Not Connected".

**Comment by Hobohome** [comment]
Hi and thanks for getting back to me. 
HPV is version 0.9.24
Android is version 5.0.2
URLs are (copy and paste) identical 
Chrome is version 72.0.3626.96    HPV reports the exact same version.
I do not have  any options for webview implementation settings.

I don't understand how HPV can display the panel correctly (and  therefore clearly  getting data from OpenHab) while still reporting "Not Connected"?
I would be keen to resolve the "not Connected" problem and see if that solves the Pi CPU usage issue. 
BTW - I've always been an IOS person, so don't assume I know what I'm doing with Android - Google has been my friend so far :-)

**Comment by vbier** [comment]
The are two connections involved. One is the browser connection that is responsible for showing HabPanel. This is identical to what chrome is doing. Then there is a second connection managed by HPV. This is used to receive commands from openHAB. The status string is derived from the second connection. This is why you can see openHAB but do not receive commands.

Do you have any items set up in the preferences? If not, HPV will not even try to connect to openHAB and will show not connected all the time.

**Comment by vbier** [comment]
And another thing: HPV should show several browser versions. The one actually in use is he one shown in the user agent. Is this the 72.0.3626.96?

**Comment by Hobohome** [comment]
Thanks for that explanation - I understand.
Yes, I have a command item, and after reading some older issues, I setup a battery status item in HPV. 
Of course none of these work due to the connection problem.

**Comment by vbier** [comment]
Then please follow the steps from https://github.com/vbier/habpanelviewer/wiki/Commanding#if-commanding-does-not-work. Most important seems to be the last point. Try this and tell me what happens.

**Comment by Hobohome** [comment]
Hi,
I carefully followed the steps as documented. When I issue the command from OH , chrome displays the event:message
data: etc
Corresponding to the command (including the json data).  So I think the sending part of the operation seems to be working.

**Comment by vbier** [comment]
And you started chrome on the same device where HPV does not work? HPV opens the same http connection that you opened on chrome when entering the rest url. I have absolutely no idea why that should not work in HPV when it works in chrome...

Can you grab an adb log? See https://github.com/vbier/habpanelviewer/wiki/How-to-generate-an-adb-log for instructions.

**Comment by Hobohome** [comment]
I decided to try clearing the OpenHab cache then rebooting the Pi. 
After doing this, the tablet now displays the OH URL in the menu as it is supposed to (yeah!) :-)
I can also see the updates to the items for Battery etc made by HPV!
However, the tablet does not respond to commands sent from OH. A test rules that issues 
Tab_Command.sendCommand("SCREEN_OFF")  has no effect. I can see the command issued in the event log.

Also (sadly) the resolved connection issue has had no effect on the CPU consumption issue. 
When running HabPanel in chrome I see a 5 minutes CPU value of 0.9 and a percentage of around 16%
When HPV is running I see 5 min CPU at 3.2 and a percentage between 65% and 85%.

**Comment by vbier** [comment]
Great.

**Comment by vbier** [comment]
What about the CPU usage?

**Comment by Hobohome** [comment]
So, on a hunch, I altered one of the items being displayed on the tablet - it was an item bound via MQTT that gets updates several times per second (I have no control over that). I created a dummy item that gets the value copied to it every 10 seconds and used this item instead of the real item in HP. Doing this resolved the high CPU issue immediately.
My guess (and of course its just a guess) is that HPV is talking just a little longer to respond to the updated item than native chrome (coz of course it is doing more). OH must be waiting (hard waiting/io waiting?) for that response - and as it is happening every few milliseconds it is causing a bottleneck.  

The only issue I have now is getting the tablet to respond to commands from OH

**Comment by vbier** [comment]
Do you have HW acceleration enabled in the preferences?

**Comment by vbier** [comment]
Regarding the commanding: open the command log in HPV and check if the command has been received. If command is red, click on it to show an error message.

**Comment by Hobohome** [comment]
Yes I did have hardware acceleration enabled - I have tried with and without this setting.
In command log the command is yellow when received - but it is not auctioned.

**Comment by Hobohome** [comment]
So problem solved! A little bit of "not properly reading the instructions" was the cause...
I read the "SCREEN_ON" command and stupidly assumed that there must be a "SCREEN_OFF" command.  This is the command I was testing with. When I used the correct command "SCREEN_DIM" it all does exactly what it should. 
Thanks very much for your help and for creating the perfect app for my purpose! It really is appreciated.

**Comment by vbier** [comment]
But the problem with the high CPU usage is still there. And I really don't understand what would be causing this. As I already said, the page rendering is done completely by the webview, which is (as long as the version is the same) the identical code that runs in chrome. As you had the problem while HPV was not even connected, there is nothing else HPV does in addition. So it should consume as much CPU (an cause as much CPU consumption in openHAB) as chrome.

I tried to reproduce this with a rule that sends 10 values per second, but the rule alone raises the CPU consumption of my PI to 60%, and opening HPV does not really add to this.

**Comment by Hobohome** [comment]
I guess in reality the CPU issue remains, but I’m happy to have found a workaround. There were actually 5 values (all updated by MQTT) that were being updated very frequently. I can reproduce the issue every time by returning HPV to the original items.

**Comment by vbier** [comment]
Can you try if the current development version improves cpu usage for you?

**Comment by Hobohome** [comment]
Sure, it might be a day or so before I’m able to do so and report back, but will do so as soon as I can.

**Comment by vbier** [comment]
Any news?

**Comment by Hobohome** [comment]
I tried to install the new version yesterday. Unfortunately I could not get it to connect to my OpenHab server. I tried for a couple of hours, but finally backed it out to the version that was working.
This process was made more difficult because I did not export the config before I changed version.

I will give this another go over the weekend - this time with an exported config.

**Comment by vbier** [comment]
What do you mean with it did not connect? It does not show the HabPanel page or it can not receive/send values from/to openHAB? There are no changes regarding the connection when compared to 0.9.24 ...

**Comment by Hobohome** [comment]
Probably best ignore the previous comment, it is very likely something that I did that stopped it from connecting.
Latest testing...
1. Export config
2. Remove release app version 
3. Install testing version
4. Import config
5. Check CPU usage with rapid update panel config.

This all went exactly as it should and I tested for about 30 min and never saw the PI CPU rise above 40% with a 5 min average at around 1.4  

To further test, I reverted back to the production version (downloaded from f-droid) and tested again with the high refresh rate values.
The PI CPU stayed around 55% and sometimes jumping to 70% however the 5 min average was 1.6
This is not as high as when I had the issue some months ago - I don't know why the change.

**Comment by vbier** [comment]
The new version has two preferences that should affect the CPU usage. "Log browser messages" and "Track Browser Connection". With both of these disabled, the app no longer looks at the browser console messages but discards them immediately. High frequent updates produce a lot of browser messages, so that reduces HPV CPU usage. 
As it looks, this also has an impact on the openHAB CPU usage, even if I do not understand why.
