### ISSUE TITLE
HPV failed to stop camera preview after taking picture

### ISSUE THREAD

**Issue by vbier** [vbier/habpanelviewer#33]
HPV fails to stop the preview. The following exception is shown in the log:

> 02-20 12:44:51.720  9099  9347 E HPV-Camera: Error restarting preview
> 02-20 12:44:51.720  9099  9347 E HPV-Camera: de.vier_bier.habpanelviewer.reporting.motion.CameraException: Konnte Vorschau nicht stoppen
> 02-20 12:44:51.720  9099  9347 E HPV-Camera: 	at de.vier_bier.habpanelviewer.reporting.motion.CameraImplV2.stopPreview(CameraImplV2.java:335)
> 02-20 12:44:51.720  9099  9347 E HPV-Camera: 	at de.vier_bier.habpanelviewer.reporting.motion.Camera.stopPreview(Camera.java:401)
> 02-20 12:44:51.720  9099  9347 E HPV-Camera: 	at de.vier_bier.habpanelviewer.reporting.motion.Camera.access$100(Camera.java:37)
> 02-20 12:44:51.720  9099  9347 E HPV-Camera: 	at de.vier_bier.habpanelviewer.reporting.motion.Camera$1$1.picture(Camera.java:306)
> 02-20 12:44:51.720  9099  9347 E HPV-Camera: 	at de.vier_bier.habpanelviewer.reporting.motion.CameraImplV2$3.onImageAvailable(CameraImplV2.java:387)
> 02-20 12:44:51.720  9099  9347 E HPV-Camera: 	at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:548)
> 02-20 12:44:51.720  9099  9347 E HPV-Camera: 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 02-20 12:44:51.720  9099  9347 E HPV-Camera: 	at android.os.Looper.loop(Looper.java:135)
> 02-20 12:44:51.720  9099  9347 E HPV-Camera: 	at android.os.HandlerThread.run(HandlerThread.java:61)

Has been reported by @sidamos as additional problem in #26.

**Comment by vbier** [comment]
I have updated the apk. Can you check if this helps and add a new log if it doesn't, please?
https://github.com/vbier/habpanelviewer/raw/master/app-debug.apk

**Comment by sidamos** [comment]
I have installed the apk from today, rebooted, attached adb, started HPV and requested a camera snapshot. Did not work. Here is the log.

[logfile.txt.gz](https://github.com/vbier/habpanelviewer/files/2885273/logfile.txt.gz)

**Comment by vbier** [comment]
There is not error message in the log, it looks like it is simply not trying to take a picture after starting the preview. I have now added more logging and built a new apk (this is a different url!):
https://github.com/vbier/habpanelviewer/raw/fixCamera/app-debug.apk

Can you once again generate a log file, please?

**Comment by sidamos** [comment]
Installed the new apk, rebooted, attached adb, started HPV, tried 2 times camera snapshot.

[logfile.txt.gz](https://github.com/vbier/habpanelviewer/files/2885941/logfile.txt.gz)

**Comment by vbier** [comment]
Do you see "Konnte Aufnahme nicht starten" as error message in the command log?

**Comment by sidamos** [comment]
No. At 1st try, I see "Sperre Kamera... Vorschau gestartet". On 2nd try, I see no additional info.

**Comment by vbier** [comment]
The first call does never complete as none of the callback methods seems to be called by the camera. The seconds command then never starts, that is why you do not see any more info.
I still do not understand why none of the callbacks is invoked and I have once again added more logging. Can you please generate another log?
https://github.com/vbier/habpanelviewer/raw/fixCamera/app-debug.apk

**Comment by sidamos** [comment]
Installed, rebooted, attached, started, camera snapshot, screenshot, camera snapshot. Both did not work. Same info in command log.

I must have broken something with my uninstalling and installing the Google apps. Or can this be a rights problem? But then it should work never. Then again, the last X tries, it did not work.

[logfile.txt.gz](https://github.com/vbier/habpanelviewer/files/2890336/logfile.txt.gz)

**Comment by sidamos** [comment]
I did some more tests. I cleared data and uninstalled HPV. I rebooted, installed HPV and did NOT restore settings. Configured everything fresh (did not enable device admin this time).
Still did not work. So, it is not a problem of restoring old settings.
Then I discovered, after force closing (swipe in recents app), the camera worked. But not always.

So, attaching a new log, where I did:
* start and try capture - did not work
* force close
* start and try capture - did not work
* force close
* start and try capture - works
* another capture - works

So, at least we have now a log where it worked.

[logfile.txt.gz](https://github.com/vbier/habpanelviewer/files/2892914/logfile.txt.gz)

**Comment by vbier** [comment]
I don't know why the camera would not work after HPV has just been started. I now remember when I was seeing this on my device, this was when I stopped the running process through the debugger. This apparently prevented unregistering from the camera (just like closing from the OS did before fixing #34), which lead to a not working camera until the next reboot.

I have now once again updated the apk. I should have fixed the problem where the first capture works but subsequent captures failed. Can you check if that improves things for you and generate a new log if it doesn't?

**Comment by sidamos** [comment]
Thanks for the update. Installed and rebooted. This time, the tablet "optimized" apps during boot. After most updates, it did not do that.
Then I started the app and made 5 snapshots successfully. Forced closed and again the same thing.
I repeated that procedure several times. All successful.
Then I rebooted again and tried that again. All successful.
So, this is looking very promising. No failures at all. I'll keep trying over the next few days. Thanks!

**Comment by sidamos** [comment]
OK, so after the night (with screen dimming), it fails again. But this time, it says "Konnte Aufnahme nicht starten" (attaching logcat). And, I can fix it with the RESTART command.

[logfile.txt.gz](https://github.com/vbier/habpanelviewer/files/2899425/logfile.txt.gz)

**Comment by vbier** [comment]
Do you think this is triggered by SCREEN_DIM or might this be some energy saving mechanism? What happend is you dim and then send a command or when you turn the tablet screen off over night and then try to capture?

**Comment by sidamos** [comment]
It is definitely the dimming (I thought this was fixed a while ago). I did this:
* reboot
* attach adb
* start HPV
* 2x capture - successful
* SCREEN_DIM
* SCREEN_ON
* 2x capture - unsuccessful ("Konnte Aufnahme nicht starten")

[logfile.txt.gz](https://github.com/vbier/habpanelviewer/files/2920231/logfile.txt.gz)

**Comment by vbier** [comment]
Another apk update. Does this fix the problem for you?
https://github.com/vbier/habpanelviewer/raw/fixCamera/app-debug.apk

**Comment by sidamos** [comment]
No. Can still be reproduced. I can make a log tomorrow.

**Comment by sidamos** [comment]
The log.
[logfile.txt.gz](https://github.com/vbier/habpanelviewer/files/2932161/logfile.txt.gz)

**Comment by vbier** [comment]
Can you once again install 0.9.24 and check if SCREEN_DIM works there? Or has you usage scenario changed (preview, motion detection)? I really do not understand why it does not work any more when it worked with 0.9.24 a few weeks ago...

**Comment by sidamos** [comment]
I uninstalled the newest version, installed 0.9.24, restored settings and tried several times making a snapshot after SCREEN_DIM/SCREEN_ON. Worked always.

**Comment by vbier** [comment]
Another update with enhanced logging. Can you please generate a new log?

If that does not help finding the problem I will replace the class that implements the camera functionality with the 0.9.24 version to make sure that this is not a side-effect introduced somewhere else.

**Comment by sidamos** [comment]
Installed the update from yesterday and did 2 successful captures, then DIM, then ON and then 2 unsuccessful captures.

[logfile.txt.gz](https://github.com/vbier/habpanelviewer/files/2939823/logfile.txt.gz)

**Comment by vbier** [comment]
Okay, I have replace the camera code with the 0.9.24 version. Can you please test if this fixes the SCREEN_DIM problem? No logs needed.

**Comment by sidamos** [comment]
No, still dead after DIM and ON. And, it can't be fixed by a RESTART command.

**Comment by vbier** [comment]
Another apk update. I have now additionally reverted all libraries to the versions used in 0.9.24. Can you test SCREEN_DIM once more, please?

**Comment by sidamos** [comment]
OK, so this version is not as reliable. After reboot, capture did not work, had to restart the app, then it worked.
But it is working fine after DIM/ON.

**Comment by vbier** [comment]
So the new version of constraintlayout seems to behave differently than the old version. I have updated the apk once more to the newest version of my code with the old constraintlayout library. This then hopefully will work reliably and after SCREEN_DIM.

**Comment by sidamos** [comment]
Still dead after DIM/ON. RESTART fixes it.

**Comment by vbier** [comment]
Apk updated, next try, please.

**Comment by sidamos** [comment]
Same thing. Dead after DIM, RESTART fixes it.

**Comment by vbier** [comment]
How did you test this? Only DIM/ON/CAPTURE or did you capture also before DIM? If you 
1. capture
2. capture
3. dim/on
4. capture
Then only 4 fails?

**Comment by sidamos** [comment]
Correct, 4. and all following are failing.

**Comment by vbier** [comment]
It didn't work with the old camera code and the updated libraries, reverting the libraries fixed it. Now I have reverted the libraries and have the new code and it does still not work. I would have bet my money on the last apk.

Another try with the apk I just uploaded, please...

**Comment by sidamos** [comment]
Install, reboot, adb, start, 3x capture (failed), RESTART, 3x capture (OK), DIM, ON, 3x capture (failed).

[logfile.txt.gz](https://github.com/vbier/habpanelviewer/files/2953302/logfile.txt.gz)

**Comment by vbier** [comment]
This does not make any sense as long as I can not reproduce the problem. I have now updated the apk on the master branch. It should not contain the changes that broke SCREEN_DIM, but should have the fixes for this problem.
Can you test if that works for you?
https://github.com/vbier/habpanelviewer/raw/master/app-debug.apk

**Comment by sidamos** [comment]
This version behaves pretty erratic. Sometimes it works, sometimes it does not. If it does not, it sometimes takes several RESTARTs to make it work again. Then it works for 1-3 snapshots and then not anymore. 
So, it makes no sense to test DIM with this version, I think.

**Comment by vbier** [comment]
This essentially is the 0.9.24 version with one camera related change that only comes into play when you terminate the app. It is hard to believe that this version is worse than 0.9.24.

**Comment by sidamos** [comment]
Do you want a log?

**Comment by vbier** [comment]
No, thanks. I have looked at enough logs. I have now tested this with two additional devices and both work as expected, so this really seems to be a Kindle Fire problem. I will see if I find somebody who owns one that I can lend to fix the bug.

**Comment by vbier** [comment]
I have now borrowed a fire hd 10 from a friend and have fixed the bug:
https://github.com/vbier/habpanelviewer/raw/fixCamera/app-debug.apk

Can you please test and confirm it also works for you now?

**Comment by sidamos** [comment]
Thanks for putting in this effort! 

After a first quick test, it works reliable, until I DIM. After ON, it does not work anymore. RESTART fixes it.

**Comment by vbier** [comment]
Next try.

**Comment by sidamos** [comment]
Very good! I tested several times and it worked every time. I'll keep testing during the next days.

**Comment by vbier** [comment]
As I haven't heard from you any more, I assume everything is working as it should.

**Comment by sidamos** [comment]
> As I haven't heard from you any more, I assume everything is working as it should.

Yep, still working. Thanks again for your effort!
