### ISSUE TITLE
Camera issue on the Nexus 10 (Lineage)

### ISSUE THREAD

**Issue by mstarczewski** [vbier/habpanelviewer#35]
Black square appears in right down screen corner. It can not be disabled via camera preferences.

**To Reproduce**
1. Start HPV
2. Go to Preferences
3. Click back
4. See black square
![image](https://user-images.githubusercontent.com/27503526/53285924-42008400-3767-11e9-904b-351e99ec4934.png)

 - Device: Nexus 10
 - OS: Andorid 7.1.2 LineageOS 14.1
 - Camera is broken in Nexus 10 with Lineage.

[logfile_nexus10.zip](https://github.com/vbier/habpanelviewer/files/2896754/logfile_nexus10.zip)

**Comment by vbier** [comment]
Can you please install this apk and generate another log?
https://github.com/vbier/habpanelviewer/raw/nexus10/app-debug.apk

**Comment by mstarczewski** [comment]
Here you go.
[nexus10_25pre.zip](https://github.com/vbier/habpanelviewer/files/2896789/nexus10_25pre.zip)

**Comment by vbier** [comment]
I have updated the apk. That should fix your problem. Can you please test?

**Comment by mstarczewski** [comment]
Now is OK. **Thank You**.
