### ISSUE TITLE
Pressure sensor interval

### ISSUE THREAD

**Issue by Grimthorr** [vbier/habpanelviewer#37]
**Is your feature request related to a problem? Please describe.**
Using the pressure sensor on a Nexus 10 causes a large number of updates to openHAB in short succession. This seems to happen when the sensor reading bounces between 2 very close values (±1).

**Describe the solution you'd like**
Implement an optional update interval for the pressure (and temperature?) sensor reporting, much like how the brightness sensor is handled. I can push a PR through for you if I get some time to test this out myself.

**Describe alternatives you've considered**
Averaging probably wouldn't work for the pressure sensor as this may lead to incorrect values.

**Additional context**
An example update spam from the pressure sensor can be seen below; notice how the pressure changes between the same 2 values, sometimes within the same second.

![screenshot](https://user-images.githubusercontent.com/5190473/53480805-d7578d00-3a73-11e9-8821-2d283abf7543.png)

**Comment by vbier** [comment]
I will look into this in the next days, as I am currently busy with real life.

**Comment by Grimthorr** [comment]
Thanks @vbier, I'll take a look later this week to do some testing, and I could always push a PR if you'd like?

The averaging might work actually; I didn't look into it fully, but I just assumed averaging the pressure and temperature values might mean the highs and lows are not reported. For example, an average between 1024 and 1025 would be 1024.5, rounded to 1025, so the value would never be reported as 1024.

**Comment by vbier** [comment]
Here is a test version that adds averaging to pressure and temperature sensors:
https://github.com/vbier/habpanelviewer/raw/averagePressure/app-debug.apk

**Comment by Grimthorr** [comment]
This is great, thanks 👍.

Although it does lose precision for the temperature value, which used to be a `float` and is now cast to an `int` at:

https://github.com/vbier/habpanelviewer/blob/2208425d481b1af414bf3ebacffb95c9b90d7eb5/app/src/main/java/de/vier_bier/habpanelviewer/reporting/AbstractAveragingDeviceMonitor.java#L58

For the same reason, it can't add the temperature status to the "Status Information" list as it throws:

> java.util.IllegalFormatConversionException: %f can't format java.lang.Integer arguments

Because the format string is still expecting a `float` value:

https://github.com/vbier/habpanelviewer/blob/2208425d481b1af414bf3ebacffb95c9b90d7eb5/app/src/main/res/values/strings.xml#L235

https://github.com/vbier/habpanelviewer/blob/2208425d481b1af414bf3ebacffb95c9b90d7eb5/app/src/main/res/values-de/strings.xml#L232

The `AveragePropagator` is using `int` values, but all [SensorEvent#values](https://developer.android.com/reference/android/hardware/SensorEvent.html#values) are provided as `float`, so would it be worth switching the averager to use `float` instead?

**Comment by Grimthorr** [comment]
I did a quick type migration of `IntAverage` to `FloatAverage` on a fork: f372fc24b98b302bacaa405f3362e82f6a0d2da6. This gains precision on the pressure, temperature and brightness values too.

**Comment by vbier** [comment]
I converted the pressure code and then thought it might be the same for temperature without really looking at the code. I will check your fork tomorrow, thanks.

**Comment by vbier** [comment]
If this works for you create a PR and i will merge it.

**Comment by Grimthorr** [comment]
Ok great thanks, I'll create a PR. Which branch do you want as the base, `master` or `averagePressure`? I think they are out of sync.

**Comment by vbier** [comment]
Use averagePressure, I will then merge to master.

**Comment by vbier** [comment]
I have just updated the apk with your PR and also made sure that no more average values are propagated once sensor reporting or averaging has been turned off.

It would be nice if you would test this once again to make sure it works and I have not overlooked something again.

**Comment by Grimthorr** [comment]
I can test on a live device tomorrow, but it works perfectly on my emulator. The only thing I did notice is:

The `AbstractAveragingDeviceMonitor` will send the first value immediately in `onSensorChanged`:

https://github.com/vbier/habpanelviewer/blob/6ea94fe068c91234b353846da1bdd2f3bddcb39d/app/src/main/java/de/vier_bier/habpanelviewer/reporting/AbstractAveragingDeviceMonitor.java#L65-L76

And `ServerConnection` also sends the first value when [`AveragePropagator#addStateToAverage`](https://github.com/vbier/habpanelviewer/blob/averagePressure/app/src/main/java/de/vier_bier/habpanelviewer/openhab/average/AveragePropagator.java#L63) returns `true`:

https://github.com/vbier/habpanelviewer/blob/6ea94fe068c91234b353846da1bdd2f3bddcb39d/app/src/main/java/de/vier_bier/habpanelviewer/openhab/ServerConnection.java#L288-L293

Other than that, it all looks good to me and ready to merge if you're happy.

**Comment by vbier** [comment]
Yes you are right. I removed this from AbstractAveragingDeviceMonitor.

**Comment by vbier** [comment]
Thanks for your help, changes have been merged.
