### ISSUE TITLE
Feature for physical motion detection using gyro

### ISSUE THREAD

**Issue by Alluuu** [vbier/habpanelviewer#39]
Hi,

I first thought motion detection was it, but it's camera based as I understand.

However it'd be great to also have motion detection based on tablet movement, not in real time of-course, that'd be bandwidth heavy (and there's too much data for any of it to be usable in raw format), but just enough, that when the movement has been minimal for a long time, and suddenly there's big ongoing movement detected by the gyro it'd update an item.

My use case is that in my media room, I have my tablet docked running the HabPanelViewer and first thing I do is take the tablet out of the dock, and as I have no other triggers to use there, it'd be great to be able to turn on the lights as soon as I pick it up.

Didn't know any other place to post this to, great work on the app!

Best,

Alari

**Comment by vbier** [comment]
Can't you use the proximity sensor for that?

**Comment by Alluuu** [comment]
@vbier - wow that's one quick reply!

However the tablet at hand is a Sony Z3 Compact tablet that unfortunately does not have a proximity sensor. Also I think the proximity sensor works only with very close proximity, that may not always be triggered, no?

**Comment by vbier** [comment]
It seems to differ from device to device how sensitive the proximity sensor is. But if you tablet does not have one, it does not matter. You can install this app that allows to turn the screen on when the tablet is moved:
https://play.google.com/store/apps/details?id=com.plexnor.gravityscreenofffree

**Comment by Alluuu** [comment]
Actually for now I just solved it with battery charging status (since it's a dock) let's see how that works out. Just this one time right now, when I put the tablet into the dock it didn't change the status and even in app info stated as not charging, taking it out and putting back in again changed it as expected. even though the tablet plugged in green light went on in both cases. Will get to test a little if and how it works with tablet not being powered and so on.

Still I think it's a cool feature to be able to trigger stuff based on movement, for instance when otherwise stationary device has been moving around for some time.

**Comment by Alluuu** [comment]
yep, for some reason the battery reporting, every time i take it out of the dock and then put it back into the dock, the state isn't changed, but when I take it off again and put it back to the dock, the state get's changed..

**Comment by vbier** [comment]
I have uploaded a test apk that contains two changes:
1. it makes sure that the app is not restarted by android when docking status changes (this might get rid of the problem that battery reporting does not work every time)
2. it adds docking state reporting, which should report whether the device is docked or not independent from the charging state
As I have no docking station to test this, it would be nice if you can install and test if this works for you.

**Comment by Alluuu** [comment]
@vbier I'll let you know when I get home :)

**Comment by Alluuu** [comment]
Maybe a dumb question, but can I just install the new APK with my current version installed and it'll update or do I have to remove the previous one first?

**Comment by vbier** [comment]
If you have currently installed an apk version, you can install over it. If you have a version from play store, you have to deinstall first. You can export your settings before uninstalling and import them again later.

**Comment by digitaldan** [comment]
I can try out the docking reporting when i’m Back in town on Sunday .

**Comment by Alluuu** [comment]
@vbier I installed the new version from the new branch

I'm not sure if I have to change some settings, because I don't see any new settings, but after the update the restarting of tablet, when docking/undocking is gone, which is nice I guess.

But even though I have the battery reporting enabled, when looking at "status information" it says that it's disabled and I can't see the state anymore.

However it still reports, becaus ethe openhab item state is updated..

I'll see if it spontaneously changes state soon, as when it's state changes to "undocked" my lights in that room will turn on. And there's nothing to turn them off, so, if the lights are on tomorrow I'll know :)

**Comment by vbier** [comment]
There should be a new preference entry under reporting - docking state. I
will look into the disabled battery thing tomorrow.

Alluuu <notifications@github.com> schrieb am Mo., 15. Apr. 2019, 20:30:

**Comment by vbier** [comment]
I just updated the apk. Now docking status is correctly shown in sys info, no longer overwriting the battery display.

**Comment by Alluuu** [comment]
I'll take a look, however the previous version I intalled is still working properly with no malfucntions, the light's still haven't turned on by themselves and the best part, the app doesn't restart every time it's undocked and redocked.

If I now install this new new version, do I have to disable the battery monitoring and enable docking monitoring? And when you say "overwrite" does this mean, that currently even with having battery monitoring on, it was actually monitoring the docking?

**Comment by vbier** [comment]
No, it was only showing the docking state as battery. That was why battery was shown as disabled even though it was reporting values.

**Comment by vbier** [comment]
Have you tested docking state reporting now?

**Comment by Alluuu** [comment]
Hey,

Both are working very well, tried plugging with cable to see it docking state also changes or not, it didn't only changes when actual deice docked.

There was a strange issue in the beginning that even though I saw the item status updating in rest/events and the status in the app's status information changed, from true to false and visa versa, for some time, the item states for both tablet_docking and tablet_charging item weren't OPEN/CLOSED but was ITEM_NOT_FOUND even though the item was correctly even receiving the statuses..

Still no functional issues and that corrected itself after a few minutes of plugging and unplugging :)

**Comment by vbier** [comment]
That is the difference between docking state and battery charging. Docking state should only toggle in dock, charging should change when it is connected to either cable or dock (and might also change while being connected).

**Comment by vbier** [comment]
@digitaldan, it would be nice if you could also test this when you have the time. If it works for you too, I would merge the changes to master so they show up in the next release.

**Comment by digitaldan** [comment]
I can confirm that the dock state is reported.

**Comment by vbier** [comment]
Thanks, @digitaldan. I have now merged the code into master.

@Alluuu, I have also added the code for your original request that uses the devices accelerometer to detect device movement. Can you please install and test?

https://github.com/vbier/habpanelviewer/raw/accelero/app-debug.apk
