### ISSUE TITLE
Panel receiving multiple commands

### ISSUE THREAD

**Issue by CrispinP** [vbier/habpanelviewer#41]
Has anyone else had a problem with repeating commands being sent to HPV?

If I send a command to HPV, say “TTS_SPEAK ‘Hello’” it arrives multiple times on the tablet.

Sent from laptop:
![image](https://user-images.githubusercontent.com/27884877/56239073-fc39ab00-6087-11e9-8379-363d8573e523.png)

What I see on the tablet:
![image](https://user-images.githubusercontent.com/27884877/56239086-052a7c80-6088-11e9-8987-37ad5a55e084.png)

![image](https://user-images.githubusercontent.com/27884877/56239111-0fe51180-6088-11e9-9833-bed5060630a0.png)

This happens to all my tablets, running either the latest HPV (0.9.25) or 0.9.22. It happens to any command sent to the tablets.

I’ve set up a rule to log when the command changes and it only fires once so it’s not OH (I don’t think)
Running OH2.4 on RPi

Anyone else had this? Any ideas?

Thread: https://community.openhab.org/t/habpanelviewer-0-9-25/34112/669?u=crispin

**Comment by vbier** [comment]
What am I supposed to say to this without logs? It does not happen for me or anybody else except you.
That is why I have not answered on the forum. It does not help if you provide a screenshot showing multiple commands. The same info is in the sentence "If I send a command to HPV, say “TTS_SPEAK ‘Hello’” it arrives multiple times on the tablet."

Provide an adb iog, openhab2 log, openhab2 event log (all containing the sending of a single command that is received multiple times), and the openhab item definition of the items involved.
Do you have any rules running on any of the involved items? Provide them, too.

**Comment by vbier** [comment]
Closed as reporter does not provide needed information

**Comment by vbier** [comment]
I have now also seen this on one of my devices. I have added debug output and are waiting for it to happen again.

**Comment by vbier** [comment]
Seems to be fixed by using OKHTTP instead of eventsource-netty.
