### ISSUE TITLE
support for webrtc?

### ISSUE THREAD

**Issue by blademckain** [vbier/habpanelviewer#42]
**Is your feature request related to a problem? Please describe.**
Habpanelviewer does not currently support webrtc.
I got the error:
Failed to get access to local media. Error name was NotSupportedError. Continuing without sending a stream.
WebRTC need both camera and microphone access.
U can try simply putting this website as start page:
https://appr.tc/

**Describe the solution you'd like**
It would be very useful if habpanelviewer supported webrtc. For example to connect a Doorbell for audio/video call

**Comment by vbier** [comment]
I have built an apk which seems to support webrtc. I have tested it with https://apprtc-m.appspot.com/. You need to enable webrtc in the preferences->browser->allow webrtc. Can you please test if this works for you?

Find the apk here: https://github.com/vbier/habpanelviewer/raw/webrtc/app-debug.apk

**Comment by vbier** [comment]
If you want me to add features, you should answer to my comments or questions. Otherwise I am going to delete the branch and close the issue.

**Comment by blademckain** [comment]
Yes it works!
Thx

**Comment by blademckain** [comment]
After more in-depth tests, I can tell you that there is still something to fix.
I have used this link in the habpanelviewer app
https://appr.tc
I click join and the website creates a new room for me.
From the PC I enter the newly created room.
From the PC I see and hear what the phone records.
But in the phone the screen remains gray, I don't see the video of the PC or the audio of the PC

**Comment by vbier** [comment]
You need to enable HW acceleration in the preferences.

**Comment by blademckain** [comment]
Yeah, with HW acceleration works!

**Comment by blademckain** [comment]
Hi vbier, thx u for your works.
I'm trying to make habpanelviewer work with this project https://github.com/kclyu/rpi-webrtc-streamer
rpi-webrtc-streamer creates a web page that can be consulted at http: // your-private-ip-address: 8889 / native-peerconnection /
similar to this https://webrtc.github.io/samples/src/content/peerconnection/pc1/
The problem is that if I visit the page from Chrome on Android it works, while if I set it as the initial habpanelviewer page, when I click Start, an icon that runs (upload) appears above the video.
But streaming doesn't start

How can I debug in order to understand where the problem lies?

**Comment by vbier** [comment]
I have no idea what exactly should happen, but if i go to https://webrtc.github.io/samples/src/content/peerconnection/pc1/ and press on start I see myself in the left video. No loading icon.

**Comment by blademckain** [comment]
yeah the https://webrtc.github.io/samples/src/content/peerconnection/pc1/ works because is a loopback
is it possible to see the **browser** console logs?
by **browser** I mean the component you use in your app to view websites

**Comment by vbier** [comment]
You need to enable browser message logging in the preferences and then you will see the messages in the adb log.

**Comment by blademckain** [comment]
i took the log with
Adb logcat -v threadtime MYIDDEVICES > C:\android-debug.log


but I don't see the browser console output

where am I wrong?

[HPV_adb_log.txt](https://github.com/vbier/habpanelviewer/files/3167933/HPV_adb_log.txt)

**Comment by vbier** [comment]
You should look for entries from chromium like

> 05-10 21:53:04.277  4398  4398 I chromium: [INFO:CONSOLE(6)] "5.514: ", source: http://192.168.14.12:8889/native-peerconnection/js/common.js (6)

These are browser log messages.

I have meanwhile updated the apk in the master branch and added an activity that allows to view the log (and to share it via android's share mechanism).

**Comment by blademckain** [comment]
ok i found the problem.
Chromium for Android support only H264 hardware acceleration, at this moment seems only EXYNOS /  QCOM GPU chip-set have this features.
chrome has h264 (software) support, chromium only h264 hardware acceleration.

**Comment by blademckain** [comment]
i think the only way at the moment is to launch the chrome app and use the webrtc videochat in there.
It is possibile use the START APP command to start chrome app in a specific url?

**Comment by vbier** [comment]
Nope.
