### ISSUE TITLE
Timer based brightnes control.

### ISSUE THREAD

**Issue by xsherlockpl** [vbier/habpanelviewer#43]
Now when my tablets finaly support recent webview habpanelviewer is working perfectly.
However I'd love to see one feature.  I have 7 tablets  in the house and they do shine a lot of light.  To be wisible during day they need to stay at full brightnes  but  during night that is very annoying.
Could you implement a timer based brighnes control that would keep a minimum brighnes in a set period of  time?

A light sensor backlit power would be a solution, but my POE tablets do not have it. :( 
Alternatively you could sample the camera to check for brightness of the room and try to set brighnes accordingly, but a timer would be easier to be done.

**Comment by vbier** [comment]
Write a rule in openhab that dies this.
