### ISSUE TITLE
Set status LED of Android Tablet

### ISSUE THREAD

**Issue by Friesoch** [vbier/habpanelviewer#44]
I have mounted my Android tablet at the wall and am using Habpanelviewer to have a nice overview. My Tablet has a Status LED to display notifications.

It would be great to be able to set the status LED to different colours like

- Constant blue If washing machines is done
- Red if any window ist open longer than 30 minutes 
- Green if everything is okay etc.

**Comment by vbier** [comment]
The only way to control the led that I have found is through notifications. I could add a command that allows to send a notification to the device where HPV is running. You could add a text to the notification and you could choose a few colors for the led.
You would then either have to dismiss the notification as normal on android devices or I could add a command to remove a notification after it has been sent.

Would this help?

**Comment by Friesoch** [comment]
sounds great! The notification-text should be optional so that i can set the status led with or without notification-text. How can the status-led then be switched off when not using notification-text to be "dismissed"?

**Comment by vbier** [comment]
I have added an apk with a test version: https://github.com/vbier/habpanelviewer/raw/notifications/app-debug.apk

It contains the new commands NOTIFICATION_SHOW and NOTIFICATION_HIDE. Check the help for usage instructions. I could only test this on my Oreo device, according to documentation it seems to work differently for older android versions.

**Comment by Friesoch** [comment]
i'll test it tomorrow Friday, thanks for this fast implementation!

**Comment by Friesoch** [comment]
I was able to install the App but when I start Habpanelviewer it crashes...

**Comment by vbier** [comment]
Can you get an ADB log?

**Comment by vbier** [comment]
Don't mind, i can reproduce the crash and will fix it later.

**Comment by vbier** [comment]
I have updated the apk.

**Comment by Friesoch** [comment]
> I have updated the apk.

I've tested the app now for 5 days and it runs :) I can set the LED in different colors and text on my Nexus 10 with Android 5.1 Version

How often does it poll for a new state? Can I set the poll-frequency somewhere i.e once a minute? (my tablet is "always on power" therefore i do not need to take care about the battery

**Comment by vbier** [comment]
It does not poll, it opens an SSE connection and updates are pushed from the server.

What happens on 5.1 if you send two notifications with the same color? Is only the second one shown or both?

**Comment by Friesoch** [comment]
The 'latest notification" wins. The first one is overwritten.  

Thanks a lot for the fast implementation of this cool Feature!!
