### ISSUE TITLE
Openhab Memory Leek

### ISSUE THREAD

**Issue by Hobohome** [vbier/habpanelviewer#46]
You may be aware of an on-going discussion regarding a memory leek in the OH core - and in particular the REST Interface (https://community.openhab.org/t/openhab-filling-up-memory-and-swap/63394) 

I am suffering from OH stability issues that seems to relate to this memory leek problem.

I have one Android tablet running habpanelviewer (and it is fantastic BTW - perfect for my needs).
I was just wondering if habpanelviewer gets the data from the REST interface each time a value is updated (like subscribing to an MQTT topic) OR is is constantly polling for changes (if so, how often?)?
The reason for the question is - I was thinking if I can reduce the frequency of the updates of the items displayed on the tablet - this may reduce the OH memory leek issue. I might be able to keep the PI stable for more than a few days.

**Comment by vbier** [comment]
This is for reporting bugs, not asking questions. If you have questions use the wiki.
