### ISSUE TITLE
Viewer can't connect to ssl socket (says not connected)

### ISSUE THREAD

**Issue by CoooLdk** [vbier/habpanelviewer#47]
## Expected Behavior
Connect to server via socket (i think) im using proxy to change port to normal https 443 port

## Current Behavior
Does not connect to https://openhab.mydomain.tld socket
If you add :443 it connects as expected

## Possible Solution
Add standard port 443 for https calls

## Steps to Reproduce (for Bugs)

1. nginx proxy with ssl
2. connect to https://openhab.mydomain.tld

## Your Environment

* OnePlus 6
* Android Version 9.0.6
* HabPanelViewer Version 0.9.22

**Comment by vbier** [comment]
I am no longer supporting version 0.9.22. Update to 0.9.25 before writing issues.
