### ISSUE TITLE
Unable to connect to over HTTP (Android 9)

### ISSUE THREAD

**Issue by yekorzh** [vbier/habpanelviewer#49]
Unable to connect to OpenHAB over HTTP, it appears thatr WebView under Android 9 requires HTTPS by default

**To Reproduce**
1) when set start page with URL using http, application shows error: net:err_cleartext_not_permitted
2) when I try connecting to openhab2 over http, application can't connect. It works over https, but value reporting doesn't

**Expected behavior**
Be able to connect to openhab over HTTP

**Smartphone/Tablet (please complete the following information):**
 - Device: Lenovo M10
 - OS: Android 9
 - Webview: Chrome 77.0.3865.116

**Additional context**
It seems that it is possible to allow webview application to use HTTP by adding 
 android:usesCleartextTraffic="true" in manifest under application tag.
EDIT: had a look at the code, and it appears that you have network security config allowing it already

**Comment by yekorzh** [comment]
I just cloned this repository, added android:usesCleartextTraffic="true" to application section in manifest, created debug apk and it is all working fine using http.

**Comment by vbier** [comment]
This has already been fixed and will be part of the next release. The APK in the master branch contains the fix if you don't want to wait

**Comment by vbier** [comment]
I just tested this and it works as expected for me with the current development version.
