### ISSUE TITLE
FR: App on f-droid

### ISSUE THREAD

**Issue by mueller-ma** [vbier/habpanelviewer#5]
Hey,
I would like to see this app f-droid, an foss app store for android. I think its easier to distribute (for people using fdroid) than downloading from github.

**Comment by vbier** [comment]
Sorry, I just saw  your issue. I am wondering why I did not get any email...

I am ultimately planning to push the app to the playstore, but can look into adding it to f-droid. Never heard of that before.

**Comment by mueller-ma** [comment]
> Sorry, I just saw your issue. I am wondering why I did not get any email...

https://github.com/settings/notifications Check `Automatically watch repositories` here and watch manually all your repos

> I am ultimately planning to push the app to the playstore, but can look into adding it to f-droid. Never heard of that before.

F-Droid is a app store for foss apps only. All apps their are built by fdroid itself, all you have to do is to tag releases and push the tags to github.

You use the official openHAB logo, which is currently not allowed: https://community.openhab.org/t/new-logo-for-openhab/35140/42 This issue has to be resolved, before I can ask to add this to fdroid.

**Comment by vbier** [comment]
Okay, I was not aware that it is not allowed to use the new logo. I will change it tomorrow.

**Comment by mueller-ma** [comment]
Can you create a release, e.g. 1.0? And can you add some metadata for fdroid like [this](https://github.com/openhab/openhab.android/pull/451)?

**Comment by txmiker** [comment]
@mueller-ma if you can you send me your email, I send you a link to the prep info (screenshots/descriptions, etc,) getting ready for the play store.  Likely will want to have the same info, etc?

**Comment by mueller-ma** [comment]
Can you upload them here in this issue? Screenshots and description isnt sensitive stuff.

**Comment by vbier** [comment]
We will add this stuff to github once we are ready.

**Comment by vbier** [comment]
@txmiker has added the information needed for publication to the playstore.

**Comment by mueller-ma** [comment]
To bring them in the correct structure, should I move or copy them?

**Comment by vbier** [comment]
Copy them, please. We can still remove the originals if we decide to keep only one instance.

**Comment by txmiker** [comment]
What is the "correct structure" you are referring to?

**Comment by vbier** [comment]
@txmiker , are you familiar with fastlane? It looks like this could be used for publishing to the playstore as well. This would get rid of any redundant information...

**Comment by txmiker** [comment]
@vbier  Not yet, but I will take a look asap

**Comment by vbier** [comment]
@mueller-ma, I have tagged a release and we have added images and descriptive text. Do you want to bring the info into the fastlane structure and create a PR?

**Comment by mueller-ma** [comment]
I'm going to make a config file for fdroid. Here is the requests For Packaging: https://gitlab.com/fdroid/rfp/issues/501

**Comment by mueller-ma** [comment]
Can you make a new tag, that also matches the version name?

**Comment by vbier** [comment]
The version name as in the release? The version in the gradle file is 0.9.16, as is the tag. If yes, can I also rename the release to 0.9.16?

**Comment by mueller-ma** [comment]
Version name is 0.9.17pre: https://github.com/vbier/habpanelviewer/blob/master/app/build.gradle#L11 and the tag's name is v0.9.16. Can you change both to (v)0.9.17 ?

**Comment by vbier** [comment]
This is the master branch that is currently not in a release state. The version in the gradle file is 0.9.16 at the time of the 0.9.16 tag.

**Comment by mueller-ma** [comment]
Ok, I wait for the next release, so the metadata is included

**Comment by vbier** [comment]
But it is not going to be different next time. Master will only contain version number 0.9.17 in the version that is tagged 0.9.17 and 0.9.18pre with the next commit. Do you need to make the release exactly when I tag 0.9.17? What is the tag then good for?

**Comment by mueller-ma** [comment]
> Master will only contain version number 0.9.17 in the version that is tagged 0.9.17 and 0.9.18pre with the next commit.

That's ok, but 0.9.16 doesn't contain any metadata, so the app would be shown as "Unknown application" in fdroid.

**Comment by vbier** [comment]
Okay, now I understand. I will do a release tomorrow even when it doors not contain anything new so we can close this issue.

**Comment by mueller-ma** [comment]
I will than create a MR with this file: https://gitlab.com/mueller-ma/fdroiddata/blob/habpanelviewer/metadata/de.vier_bier.habpanelviewer.txt
Version name is 0.9.17, version code is 1 and commit name v0.9.17.
Commit names will always be `v` followed by the version name, right?

**Comment by vbier** [comment]
Yes, if I do not forget it. We'll see if I still remember tomorrow. :wink:

**Comment by vbier** [comment]
I have released 0.9.17. I hope you can use this as is.

**Comment by vbier** [comment]
@mueller-ma, I am going to make another release today. I am planning on removing to "v" before the version from the release and the commit messages to make it more consistent. It would be nice to know if this will be a problem beforehand.

**Comment by mueller-ma** [comment]
@vbier The repo contains a jar file, which is against the fdroid inclusion policy. Can you replace that with a gradle depency?
Removing the v is not a problem, I can change the fdroid config file.

**Comment by vbier** [comment]
I have made the jar myself of a patched version of a github project. How do I define a gradle dependency for this?

**Comment by mueller-ma** [comment]
Fork the repo, make the change and then use https://jitpack.io/ to include it as gradle depency.
I don't know what changes you made, but maybe you can send them to upstream.

**Comment by vbier** [comment]
I have now changed the dependency and created the 0.9.18 release. The v is removed everywhere, so it is only 0.9.18.

**Comment by mueller-ma** [comment]
I've updated the fdroid config file accordingly.

**Comment by vbier** [comment]
Is there anything else to do or do we now only have to wait for fdroid to process your request?

**Comment by mueller-ma** [comment]
For now we just have to wait until the MR is merged and the server builds the app (that happens about once a week).
For the future you can do two things:
1. Increase versionCode with every new version. Otherwise updates are not shown in fdroid (and maybe also not in play store)
2. Add changelog to fastlane file like [this](https://github.com/Freeyourgadget/Gadgetbridge/tree/master/fastlane/metadata/android/en-US/changelogs). The number is the versionCode.

**Comment by vbier** [comment]
@mueller-ma , is it normal that it takes so long or is still something missing for the MR to be processed? 

I saw that there is a missing checkmark for "Builds with fdroid build" on https://gitlab.com/fdroid/fdroiddata/merge_requests/2920.

**Comment by mueller-ma** [comment]
> I saw that there is a missing checkmark for "Builds with fdroid build" on https://gitlab.com/fdroid/fdroiddata/merge_requests/2920.

This is because I don't have a fdroid server to test the build, but I'm fairly sure it will build with fdroid. 
No fdroid maintainer had a look at this MR, so no idea when it will be merged.

**Comment by mueller-ma** [comment]
It's available on F-Droid https://f-droid.org/en/packages/de.vier_bier.habpanelviewer/.
Can you remove the fastlane/.../title files (it's auto fetched from the apk) and make sure short_description is under 80 chars?

**Comment by vbier** [comment]
Done. Thanks for you help in setting this up.
