### ISSUE TITLE
Noise/db reporting

### ISSUE THREAD

**Issue by haesslo** [vbier/habpanelviewer#50]
Hi Vbier

## Expected Behavior

It seems not many people use noise detection in Openhab, but I would love to see it also integrated in Habpanelviewer like light, motion or other values measusred and reported to openhab.

## Possible Solution

There are quite some examples (like : https://stackoverflow.com/questions/7197798/get-the-microphone-sound-level-decibel-level-in-android) how to measure noise or db in Android.
Results to be reported just like any other sensor back to openhab item.

## Your Environment

* Device: Lenovo Tab
* Android Version: 4.4.2
* HabPanelViewer Version

Thanks for considering..

**Comment by vbier** [comment]
This might also help: https://androidexample.com/Detect_Noise_Or_Blow_Sound_-_Set_Sound_Frequency_Thersold/index.php?view=article_discription&aid=108&aaid=130

**Comment by peter88d** [comment]
it would be a wonderful feature to detect presence and detect and defend against noise :) I have been looking for a long time for any openhab loudness meter

**Comment by vbier** [comment]
Yes. And it would be wonderful if somebody would implement it and create a pull request as I do not have the time.

**Comment by vbier** [comment]
I have just uploaded an apk that has a experimental noise level reproting. Can you please test if this works for you?

https://github.com/vbier/habpanelviewer/raw/master/app-debug.apk
