### ISSUE TITLE
Fullscreen-Activity: Title bar is hidden behind the notch

### ISSUE THREAD

**Issue by DrMarkEy** [vbier/habpanelviewer#52]
The title in the HabPanel view is hidden behind the notch on my Wiko View 2. 
Unfortunately I can not capture this behaviour in a screenshot, as the notch is not visible on screenshots.

See https://developer.android.com/guide/topics/display-cutout for some information about display cutouts and how to support them.

**Comment by vbier** [comment]
Are talking about the panel title when kiosk mode is not used? There is no problem with this on my Mi8. Habpanel title is correctly rendered below the notch.

**Comment by vbier** [comment]
Reopen if you are willing to provide more information.
