### ISSUE TITLE
Login window does not offer a "store credentials" option

### ISSUE THREAD

**Issue by nrobadey** [vbier/habpanelviewer#53]
The help file mentions "a checkbox allowing to store the credentials" in the login dialog.
The is no such thing on my device (Android 7.0).
The login box opens, displays Username and Password fields, "CANCEL" and "OK" buttons, and that's it.
I can login by (1) entering the credentials each time I start the app, or (2) by adding the credentials to the URL; (1) is pretty unusable, and (2) very insecure.

![habpanelviewer_no_save_cred](https://user-images.githubusercontent.com/17157981/71472367-0c875580-27d3-11ea-817c-2490ebead8b4.png)

**Comment by vbier** [comment]
Which version are you using?

**Comment by nrobadey** [comment]
The version available in Google's "Play Store", which is 0.9.22

**Comment by nrobadey** [comment]
Ok now I see that it's a feature that has been added in rev. 0.9.23. Sorry I didn't read the release notes for this version. I'll install the APK form Github.

**Comment by vbier** [comment]
If you have password protected your rest connection it is better to install the apk from the master branch, as it contains some valuable fixes. I will do a release in the next days.
