### ISSUE TITLE
Delayed clicks

### ISSUE THREAD

**Issue by bulletprooffool** [vbier/habpanelviewer#54]
I’m running an old galaxy tablet as a wall panel and there is no available firmware update.
As such, I’m running the old Android web view (v30)

I’ve built an aggregated multimedia remote - and I need this to be responsive for when scrolling through screens and screens of channels.

I struggled for ages, but eventually found a workaround that enabled quick access to button presses, by registering my trigger events on buttons using ng-touchstart rather than ng-onclick events.

Whilst this working works wonderfully on my iPhone etc, it is hit and miss in the android tablet.

For some reason, it seems that the workaround allows every button click to trigger from habpanel to my OH server when I run Habpanel in Chrome
Chrome version is 79.0.3945.136

If however, I load the same panel in either HabPanelViewer or FullyKioskBrowser - I simply do not seem to get all event (seems that if two clicks are within about 300ms of each other, I still only get one event, like I did before implementing the workaround)
Of course, since this is a wall mounted tablet, I’d like to be able take advantage of features like managing the tablet remotely.
Is there an easy way to get FKB or HPV to use the Chrome engine for page rendering?

This is how I previously fixed this for Ios - seems the same applies to android. [SOLVED] Habpanel fast clicking in IOS https://community.openhab.org/t/solved-habpanel-fast-clicking-in-ios/83952

**Comment by vbier** [comment]
As I wrote no the forum, there is no way to get HPV or FKB to use chrome as rendering engine on Android < 7. Apps can not choose a rendering engine, they use the one that is provided by the System. Starting from Android 7, the OS allows to select the rendering engine that is provided to apps in the developer settings.

**Comment by bulletprooffool** [comment]
Thanks - appreciate the response.
