### ISSUE TITLE
Black rectangle covers half the screen

### ISSUE THREAD

**Issue by ewallquist** [vbier/habpanelviewer#57]
I have a chap tablet, Denver TAQ-70 running Android 8.1.0 on which I am running hpv 0.9.22.

When starting hpv everything looks fine but if I go to setting and then back, or if I send a screen_dim command and then a screen_on, the bottom half of the tablet seems to be covered by a black rectangle hiding all the icons. 

When restarting the app everything looks normal again until I repeat as stated above.

**Expected behavior**

![Screenshot_20200218-003017](https://user-images.githubusercontent.com/42438643/74770585-d4f5d080-528c-11ea-9939-abb6153dae82.png)

ignore the white box on top, I had some trouble getting the screenshot :-)

**Comment by vbier** [comment]
Update to 0.9.26 please.

**Comment by ewallquist** [comment]
Thanks. works like a charm. Love this app.
