### ISSUE TITLE
Great thanks for the development!

### ISSUE THREAD

**Issue by bd8392** [vbier/habpanelviewer#60]
Hi :-) I just wanted to use this place to say a great thank you for the development! The functionality is amazing and solves a lot of problems! :-) really cool app! Keep up the amazing work!

Ps: you maybe should get the app off the play store. (As I assume the F-Droid version is much newer :-) Maybe a link can be mentioned in the openhab-docs :-)

**Comment by vbier** [comment]
Unfortunately, i do not own the Google account, so i can not remove the app from the play store.

@txmiker , can you please remove the app from the play store and also remove my e-mail address from your account?
