### ISSUE TITLE
Add a command for bringing HPV to the foreground if another app is currently running

### ISSUE THREAD

**Issue by vbier** [vbier/habpanelviewer#62]

**Comment by CSchlipp** [comment]
Isn't this the current behavior of "SCREEN_ON xxx"?
If I have e.g. Kodi running and then send a "SCREEN_ON 30" command, HPV will be brought to the foreground.

**Comment by stefan-muc** [comment]
Can confirm - it will be brought to foreground, but it also changes displayed page to configured *Start page*

**Comment by binderbei** [comment]
Hi,
are you using Android 10?
In my case with Samsung Galaxy Tab A on Android 10 
Tablet_Command.sendCommand("SCREEN_ON 60") does not bring HPV to front if another app was on front before :-(

**Comment by CSchlipp** [comment]
> Hi,
> are you using Android 10?
> In my case with Samsung Galaxy Tab A on Android 10
> Tablet_Command.sendCommand("SCREEN_ON 60") does not bring HPV to front if another app was on front before :-(

In my case it works with FireOS 7, based on Android 9.

**Comment by vbier** [comment]
I have just uploaded an apk that has a TO_FRONT command. Can you please test if this works for you?

https://github.com/vbier/habpanelviewer/raw/master/app-debug.apk

**Comment by binderbei** [comment]
Hi @vbier ,

sorry I had to update everything and could test it a few minutes ago. 
Now am on OH3 but the TO_FRONT command does not work for me unfortunately :-(

Regards

Jochen
