### ISSUE TITLE
Startup failure when connecting to Openhab 3.0

### ISSUE THREAD

**Issue by imaginator** [vbier/habpanelviewer#63]
Openhab 3.0 nightly snapshot

Autodiscovered server on: `http://openhab.imagilan/habpanel` Nginx configuration (standard reverse proxy): https://github.com/imaginator/system/blob/master/salt/openhab-server/files/other-configs/nginx-openhab.conf#L5-L16

Firefox on Desktop:
```
openhab.imagilan 10.7.11.25 - - [16/Nov/2020:12:26:10 +0000] "GET /rest/items HTTP/1.1" 200 431480 "http://openhab.imagilan/habpanel/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0"
```

Loads: 

![image](https://user-images.githubusercontent.com/469572/99254244-56759180-2812-11eb-8856-a0ba0d2120c1.png)

Habpanelviewer (0.9.26):
```
openhab.imagilan 10.7.9.109 - - [16/Nov/2020:12:29:09 +0000] "GET /habpanel//rest/events?topics=smarthome/items/dummyItemThatDoesNotExist/statechanged HTTP/1.1" 404 5 "-" "okhttp/4.2.2"
```
Just shows as unable to connect but does reach nginx.

It looks like the problem is ``habpanel//rest`` but I'm not sure how to debug this further. I have attached a debug log from the app if that can help.

[bluetooth_content_share(1).txt](https://github.com/vbier/habpanelviewer/files/5546244/bluetooth_content_share.1.txt)

**Comment by vbier** [comment]
The server URLis wrong. It should not have habpanel/ at the end.

**Comment by imaginator** [comment]
Thanks @vbier. Using a server url of just `http://openhab.imagilan/' shows the new 3.0 admin page. Adding a Start Page of `/habpanel/#/view/logs' / `/habpanel/` or `/habpanel/#` results in a white screen. I have attached a log file.  I can confirm that, for example, `http://openhab.imagilan/habpanel/#/view/logs` is working on my browser.

[bluetooth_content_share.html.txt](https://github.com/vbier/habpanelviewer/files/5554370/bluetooth_content_share.html.txt)

(some hours later)

It looks like the issue is https://community.openhab.org/t/oh-3-habpanel/108045/3 (lack of a default panel / configuration). I'll close this issue now and reopen once this gets cleared up in 3.0.
