### ISSUE TITLE
White page on old Android with OpenHab3. The problem does not occur with Openhab 2.5 

### ISSUE THREAD

**Issue by peter88d** [vbier/habpanelviewer#64]
I'm using an app on my old HTC Desire phone. While it works great with Openhab 2.5, after migrating to Openhab 3 it only shows a white screen - I guess there is a problem with the login page. This is strange because the browser is working fine. 

**To Reproduce**
1. Install app on Android 4.4 for Openhab 3
2. Pass intro screens / or use go to page (habpanel page)
4. See error - white screen / page

**Smartphone/Tablet (please complete the following information):**
 - Device: HTC Desire
 - OS: Android 4.4.2
 - Version e.g. 0.9.24  [downloaded from Google Play 06.02.2021]

**Comment by vbier** [comment]
Version 0.9.24 is no longer supported.
