### ISSUE TITLE
Red border won't go away

### ISSUE THREAD

**Issue by politas** [vbier/habpanelviewer#65]
**Describe the bug**
App displays ugly red border for no apparent reason

**To Reproduce**
1. Open app

**Expected behavior**
The panel I have set as my start page should load, without an added red border

**Screenshots**
![Screenshot_20210208-200517](https://user-images.githubusercontent.com/2109967/107199419-7f40a800-6a4a-11eb-8703-57da9ae175c5.jpg)

**Smartphone/Tablet (please complete the following information):**
 - Device: OnePlus 6
 - OS: Android 10 (Oxygen OS 10.3.8)
 - Version 0.9.26

**Additional context**
If this red border is intended to show something, I don't know what.

**Comment by vbier** [comment]
It would bei nice of you at least try to find out what the problem nicht be before reporting functionality ad bugs: https://github.com/vbier/habpanelviewer/wiki/Red-Border

**Comment by politas** [comment]
Ah, I see. You've just decided that http connections are inherently problematic. I actually tried to follow a link in the app to a defunct forum thread. Well, don't worry, you won't be getting any more bug reports from me.

**Comment by vbier** [comment]
You either do not seem to have read the page, or you did not understand what i wrote. Either way, If you don't follow the advice there is nothing i can do.
