### ISSUE TITLE
Add a setting that prevents the screen from turning off

### ISSUE THREAD

**Issue by SaschaSchaefer** [vbier/habpanelviewer#66]
I'm fairly new to the project and am looking for a way to keep my tablet's screen active, while HPV is running. Maybe I completely misunderstood the current implementation, or maybe there is an option that I didn't find.
I read a bit into the commands and noticed that it is possible to activate this setting, by having my openhab instance send a command to my tablet. I think doing it this way is rather complicated and was wondering if there might be an easier way.

I would prefer a simple setting in the app, that enables the option. 
Besides, I do not want to apply this setting to my phone, only to the tablet.

**Comment by vbier** [comment]
Sorry. As I have not much time, I am not going to add improvements that do not provide extra functionality (even though it might be more complicated, what you need is possible by sending a command).

You can implement this yourself and create a pull request if you want.

**Comment by SaschaSchaefer** [comment]
No problem. I'll see if I find the time to implement this and send a pull request.
...Or maybe I'll just use the command approach after all 😅

**Comment by bf8392** [comment]
@SaschaSchaefer you can use the app screen on from F-Droid... working perfectly :-)

**Comment by SaschaSchaefer** [comment]
That's good to know, thanks for the tip!
