### ISSUE TITLE
HPV crashes on startup

### ISSUE THREAD

**Issue by jeroenhendricksen** [vbier/habpanelviewer#67]
[Related OpenHAB community post](https://community.openhab.org/t/habpanelviewer-0-9-26/34112/973?u=randomname)

**Describe the bug**
HPV crashes at startup  

**To Reproduce**
1. Given the below mentioned version of HPV is cleanly installed, start HPV by clicking the HabPanelViewer icon on de Android desktop
2. HPV shows it has crashed (see attached debug log)

**Expected behavior**
HPV should have started normally

**Screenshots**
It's just a general popup from the Android system saying "HABPanelViewer is gestopt" after which is gives me two options: "App opnieuw openen" (which obviously doesn't fix the problem) and "Verbergen tot apparaat opnieuw wordt opgestart".

**Smartphone/Tablet (please complete the following information):**
 - Device: HTC Nexus 9 tablet
 - OS: Lineage OS `15.1-20190613-UNOFFICIAL-FLOUNDER` running Android version `8.1.0`
 - Version: Downloaded from `https://github.com/vbier/habpanelviewer/blob/master/app-debug.apk` at March 23 2021, which identifies itself as `0.9.27pre`.

**Additional context**
See the attached android adb debug log:

[hpv_stacktrace.txt](https://github.com/vbier/habpanelviewer/files/6202823/hpv_stacktrace.txt)

Earlier (stable) versions of HPV did work on this devices with the same configuration mentioned above properly. As mentioned in the OpenHAB community thread I have two other tablets suffering from HPV startup crashes. For now, I'd like to focus on this specific android device to not make it more complex.

**Comment by vbier** [comment]
I tried to reproduce this with the android emulator but failed. Can you tell me which version you used last that worked so I can see if any of the changes looks as if it could be the cause?

**Comment by jeroenhendricksen** [comment]
> I tried to reproduce this with the android emulator but failed. Can you tell me which version you used last that worked so I can see if any of the changes looks as if it could be the cause?

The working version is the latest version from the PlayStore, which seems to be `0.9.22`. This surprises me, because `0.9.26` should have been the latest one, right?

**Comment by jeroenhendricksen** [comment]
to elaborate further, I've tried installing older versions until it worked again for my HTS tablet. That might help you find the code change that causes this:

- `0.9.27pre` --> crashed
- `0.9.26` --> crashes
- `0.9.25` --> HPV starts normally

Please let me know if you need any other stacktrace or debug log.

**Comment by vbier** [comment]
The playstore is not maintained by me. Another user uploaded versions there for some time but does no longer. I asked him to remove the app from the playstore as the version is completely outdated, but he did not.

0.9.25 is two years old, a lot has changed from then. I will try to see if I find something. Would you be willing to install some HPV apks to test out things?

**Comment by jeroenhendricksen** [comment]
> The playstore is not maintained by me. Another user uploaded versions there for some time but does no longer. I asked him to remove the app from the playstore as the version is completely outdated, but he did not.

Hmm, that seems hard to "fix". You could maybe add your version to the play store yourself (automated of course), but with the word "official" in it. But, I guess the user base using the HPV app is mostly already on the OH community forum and probably has no problem installing it from an APK file they have to download themselves.

> 0.9.25 is two years old, a lot has changed from then. I will try to see if I find something. Would you be willing to install some HPV apks to test out things?

Thank you for trying to fix this. I'd be happy to test custom APK's for you.

**Comment by vbier** [comment]
Can you try this apk please: https://github.com/vbier/habpanelviewer/raw/620ddee167e64e3b5ca57d96e69164da02457e7a/app-debug.apk

**Comment by jeroenhendricksen** [comment]
> Can you try this apk please: https://github.com/vbier/habpanelviewer/raw/620ddee167e64e3b5ca57d96e69164da02457e7a/app-debug.apk

I did, and it crashed immediately at startup, same as before. The APK version it installed was `0.9.26pre` (to verify I've installed the above one).

[hpv_stacktrace_2.txt](https://github.com/vbier/habpanelviewer/files/6253223/hpv_stacktrace_2.txt)

Let me know if I need to test some more.

**Comment by vbier** [comment]
Too bad. That was the last version before the changes I thought could have broken the app. Let's try it the other way round, I have built an apk were I removed the Intro, which seems to be the culprit. Can you test if this woks as expected:
https://github.com/vbier/habpanelviewer/raw/investigateCrash/app-debug.apk

**Comment by jeroenhendricksen** [comment]
> Too bad. That was the last version before the changes I thought could have broken the app. Let's try it the other way round, I have built an apk were I removed the Intro, which seems to be the culprit. Can you test if this woks as expected:
> https://github.com/vbier/habpanelviewer/raw/investigateCrash/app-debug.apk

It still crashes. It says version `0.9.27pre`.
[hpv_stacktrace_3.txt](https://github.com/vbier/habpanelviewer/files/6260210/hpv_stacktrace_3.txt)

**Comment by vbier** [comment]
Can you re-download from the same URL and try again, please?

**Comment by jeroenhendricksen** [comment]
> Can you re-download from the same URL and try again, please?

There is a stacktrace during startup, but HPV starts properly. It seems to work properly genuinely, except for some other exceptions ([hpv_stacktrace_4b.txt](https://github.com/vbier/habpanelviewer/files/6273710/hpv_stacktrace_4b.txt))

This is the stacktrace from the HPV startup:
[hpv_stacktrace_4.txt](https://github.com/vbier/habpanelviewer/files/6273656/hpv_stacktrace_4.txt)

I hope this feedback helps you out. Let me know if there is a new version you need to have tested.

**Comment by jeroenhendricksen** [comment]
I've test the latest 'investigateCrash' version on my Lenovo tablet as well. It started properly and I could configure it, but after configuring values to be reported (specifically the battery level, though I'm not sure this specific one is the root cause) HPV crashed and kept crashing. In the logs I found a crash dump. The difference with earlier versions is that I can erase the cache & storage for HPV and am then able to re-configure the app, after which the same problem repeats, wehen I repeat the above described Value reporting. See the attached stacktrace:
[hpv_stacktrace_v5.txt](https://github.com/vbier/habpanelviewer/files/6278529/hpv_stacktrace_v5.txt)

**Comment by vbier** [comment]
The stacktraces in hpv_stacktrace_4 are just dummy exceptions i used to get a stacktrace into the log. You can safely ignore them. 

Judging from the stacktrace from hpv_stacktrace_V5.txt, the problem seems to be a native crash in the webview component. This should have nothing to do with value reporting, but only with the page shown in HPV. Is this possible? Did you also change the start pagen when setting up HPV? Do you have dynamic content on the page? Can you reproduce the problem with your other tablet?

You can try to disable HW acceleration in HPV settings, or set a different webview in android settings, or update the webview component using the play store.

**Comment by jeroenhendricksen** [comment]
> The stacktraces in hpv_stacktrace_4 are just dummy exceptions i used to get a stacktrace into the log. You can safely ignore them.

Great, I'll ignore them.

> Judging from the stacktrace from hpv_stacktrace_V5.txt, the problem seems to be a native crash in the webview component. This should have nothing to do with value reporting, but only with the page shown in HPV. Is this possible? Did you also change the start pagen when setting up HPV? Do you have dynamic content on the page? Can you reproduce the problem with your other tablet?

> You can try to disable HW acceleration in HPV settings, or set a different webview in android settings, or update the webview component using the play store.

I did change the start page, and the start page url also works in Chrome (which is not the webview component that was selected as the default). I have HW acceleration already disabled and intend to keep it disabled. I also do have dynamic content on the page (a web image widget displaying a camera feed which is refreshed at a pretty short interval). I couldn't reproduce this problem on the other tablet. Then I did found that indeed an update was pending for the webview component and after updating it, it suddenly worked! I didn't expect that would solve the issue, but it did.

It seems all my problems are solved and I can use all of my tablets with HPV again with OH3. I'll keep a lookout for the new stable release so I can upgrade it when the time is there. Thanks again for your time and effort helping me out!

**Comment by vbier** [comment]
You closed the issue a little bit too fast. I have only identified (and removed) the cause, but have not yet found a fix.

**Comment by jeroenhendricksen** [comment]
> You closed the issue a little bit too fast. I have only identified (and removed) the cause, but have not yet found a fix.

Sorry for that. Ik closed it because you actually solved my issue with the latest build and additional comment. Good thing you reopened it.

> Edit: I have just updated the apk again. Can you please test if it still works?

I just tested in on both the Lenovo and HTC tablet by updating/overwriting the existing HPV version (without clearing cache/storage). The HPV version it shows is `0.9.27pre (14-04-2021 14:56)`. This version works properly on both of my devices. I've included both `adb logcat` outputs, as this might help you further:

[hpv_lenovo_v6.txt](https://github.com/vbier/habpanelviewer/files/6313236/hpv_lenovo_v6.txt)
[hpv_htc_v6.txt](https://github.com/vbier/habpanelviewer/files/6313237/hpv_htc_v6.txt)

**Comment by vbier** [comment]
Thanks, that is good. To make sure, can you delete app data for HPV in android settings so that the intro is started next time you start HPV? If you then restart, after the intro you should see a screen checking power saving permissions and asking for db setup. Do you see the HPV icon on this screen?

**Comment by jeroenhendricksen** [comment]
> Thanks, that is good. To make sure, can you delete app data for HPV in android settings so that the intro is started next time you start HPV? If you then restart, after the intro you should see a screen checking power saving permissions and asking for db setup. Do you see the HPV icon on this screen?

I do get the power saving permissions screen (again, after I've reset the setting) and I do see the HPV logo on this screen!
