### ISSUE TITLE
OpenHAB 3.0 with Android 4.4 and habpanelviewer

### ISSUE THREAD

**Issue by batevladi** [vbier/habpanelviewer#68]
Hello Volker! 

What is necessary to have the latest version of habpanelviewer to work with Android 4.4? I have an old device, but now that I am working with OH3, the habpanelviewer does not want to load the panels (no default panel error, even if I fix the default setting the panel config - and there is just one panel).

Thanks a million for the app! 

I have manage to install on 4.4. from FDroid but it crashes when trying to open preferences, accepts the URL but errors out again with No default panel configuration - although the pannel works on a browser.

**Comment by vbier** [comment]
It is not possible, that is why HPV does no longer support Android 4.4. Webview coming with android 4.4 is lacking features and compatibility with openHAB UIs. As I have already explained in the forum, there is a difference between the browser (which can be updated) and the webview component (which can not be updated).
