### ISSUE TITLE
app-debug.apk failes  to install

### ISSUE THREAD

**Issue by koshisan** [vbier/habpanelviewer#69]
**Before reporting bugs, make sure you have searched for your problem in the openHAB community thread at: https://community.openhab.org/t/habpanelviewer-0-9-25/34112** <- That page doesn't exist

**Describe the bug**

I was forced to update to Openhab3 because of the Openhab2 repository being taken down. This requires me to update all applications that communictate with Openhab through its API - including habpanelviewer which I run on several tablets around the house.

Since there doesn't seem to be a compatible release with Openhab3, I tried to install the app-debug.apk instead. However, this only works on a single device in the household. All other tablets (notably multiple Amazon Fire HD 10 9th gen tabs, but also an older chinese one) fail to install the apk. Unfortunately Android isn't very verbose, I only get an "app not installed" error. 

**To Reproduce**

Any attempt to install app-debug.apk on the mentioned devices

**Smartphone/Tablet (please complete the following information):**

* Amazon Fire HD 10 9th gen
* HiBook Pro

Note: All Tablets are running android versions higher than 4.4, so they should be supported according to the documentation...

**Additional context**
Is there any way I could get more meaningful debug information to sort this out?

**Comment by vbier** [comment]
Have you uninstalled HPV before installing?

**Comment by koshisan** [comment]
... of course I haven't, since I wanted to keep my settings... 
But after uninstalling it does indeed work for all devices!
Thanks for the quick support :)
