### ISSUE TITLE
Commanding only works randomly

### ISSUE THREAD

**Issue by MrMontesa** [vbier/habpanelviewer#70]
**Describe the bug**
The Commad item is properly set in OH3, but the tablet does not seem to pick them up properly. I'm currently testing, sending lots of commands via openhab-cli, but only very few commands are interpreted by HPV. Specially I only see SCREEN_ON in the HPV command log.
Sending the Battery Status or Lux value from the tablet towards OH3 works like charm.

**To Reproduce**
```
openhab> openhab:items list gGfCorridorTablet*
gGfCorridorTablet_Command (Type=StringItem, State=KEEP_SCREEN_ON, Label=EG Tablet Command, Category=, Tags=[Status], Groups=[gGfCorridorTablet])
gGfCorridorTablet (Type=GroupItem, Members=4, State=NULL, Label=EG Flur Tablet, Category=tablet, Tags=[Screen], Groups=[gGfCorridor])
gGfCorridorTablet_Motion (Type=ContactItem, State=CLOSED, Label=EG Tablet Bewegung, Category=, Tags=[MotionDetector], Groups=[gGfCorridorTablet])
gGfCorridorTablet_Bat (Type=NumberItem, State=100, Label=EG Tablet Batterie, Category=battery, Tags=[Battery], Groups=[gGfCorridorTablet])
gGfCorridorTablet_Lux (Type=NumberItem, State=3.9130435, Label=EG Tablet Helligkeitssensor, Category=, Tags=[Sensor], Groups=[gGfCorridorTablet])

openhab> openhab:send gGfCorridorTablet_Command KEEP_SCREEN_ON
Command has been sent successfully.
```
OH3 log sais:
```
2021-09-16 11:32:22.611 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'gGfCorridorTablet_Command' received command KEEP_SCREEN_ON
2021-09-16 11:32:22.615 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'gGfCorridorTablet_Command' changed from SCREEN_ON to KEEP_SCREEN_ON
```
The Command log in HPV on the tablet remains empty. And even if the command log seldomly shows a SCREEN_ON message with the date, nothing happens on the tablet itself.

**Screenshots**
![HPV-setting-FireHD10](https://user-images.githubusercontent.com/600125/133590336-b356cf2e-f0ed-48be-83f8-51c2d0f6330a.jpg)

**Smartphone/Tablet (please complete the following information):**
 - Device: Amazon Fire HD10
 - OS: rooted FireOS
 - user agent 59.0.3071

**Additional context**
Sometimes HPV shows red boarder in rage mode. Then restarting HPV is the only option to make it work again.

https://user-images.githubusercontent.com/600125/133591055-f4456326-1cfb-4fb7-8df4-e37976c41a7b.mp4

Any idea how to troubleshoot the commanding issue in more detail?
thanks for your help.

**Comment by MrMontesa** [comment]
Did some more tests with my Samsung Tab S6.
Just configured the tablet for the same commands as the wall tablet and most commands are properly shown in command log as well as actions on the sreen. e.g. SCREEN_ON, SCREEN_OFF, etc works.
But as soon as I send a "SET_BRIGHTNESS 10" the command is not received in command log in HPV nor any dimming is physically done to the tablet.
All subsequent commands fail until I restart HPV app. Then I can continue to command the device.

**Comment by Alpoy** [comment]
I'm having the same problem, the commands don't work. Can't see any commands in the debug or command log. This worked fine before upgrading to OH3.1 from OH2. Values in the habpanel view itself are updating as expected. 
Running 0.9.26

**Comment by malfurion** [comment]
i have the same problem.

i'm on OH 3.1.0 and HVP 0.9.26

the command log is empty and my tablet is not doing any of the actions

i've tried SCREEN_ON, TO_FRONT and RELOAD.

**Comment by domoticsduino** [comment]
Hi, same problem here. OH 3.2 M2 and HVP 0.9.26.

No command reaches HVP...no action performed and no log in command log.

With OH2 it worked perfectly

Marco

**Comment by vbier** [comment]
Guys, getting NO commands is not the same problem as getting only SOME commands. If you would have taken the time to read documentation you would know what your problem is.

@MrMontesa, there are some other people using HPV on a Fire tablet. It might help if you ask on the wiki page if somebody else had the same problems. Does this happen when the device screen is off (power-saving?) or also when the screen is on? The red border indicates connection problems. Does this match to the time when no commands are received?

Regarding the SET_BRIGHTNESS command: send it, generate an adb log on the device and send it to me.

**Comment by domoticsduino** [comment]
Hi,
I read the documentation many times (I mean Wiki pages and App's help file) but the only things related to commands is the power saving option that I already turned off globally and also for HPV. Maybe version 0.9.26 is not compatible with OH3 and command managements? Because in the preferences section I cannot find the possibility to choose OpenHAB Server version near OpenHAB Url and in the App's Help file it is mentioned.

**_openHAB version
The version of your openHAB server.
Starting with OH3, the names of the SSE topics have changed, so that HPV will no longer get item updates when the openHAB version is not correctly set._**

Or maybe I'm missing anything else?

Thanks for your work.

**Comment by domoticsduino** [comment]
**Update**

I installed version **0.9.27pre** directy from https://github.com/vbier/habpanelviewer/blob/master/app-debug.apk and now commands are executed and logged.

**Comment by malfurion** [comment]
> Guys, getting NO commands is not the same problem as getting only SOME commands. If you would have taken the time to read documentation you would know what your problem is.
> 
> @MrMontesa, there are some other people using HPV on a Fire tablet. It might help if you ask on the wiki page if somebody else had the same problems. Does this happen when the device screen is off (power-saving?) or also when the screen is on? The red border indicates connection problems. Does this match to the time when no commands are received?
> 
> Regarding the SET_BRIGHTNESS command: send it, generate an adb log on the device and send it to me.

ive read the documentation and did everything mentioned there the only thing ive didnt found was the option to set the server version to oh2 or oh3 so perhabs this is the problem but were is this option ?

**Comment by MrMontesa** [comment]
@vbier Thanks for the info. I'll get you an ADB log for the SET_BRIGHTNESS issue.

The Fire tablet issue, is permanent. No difference if wake or sleep. The screen of the table is ON and I'll send a DIMM or OFF command, nothing happens.
I do see few commands in the histroy log seldom on the device, but they havent had any physical reaction on the device. e.g
I send 10 commands over a time of 5mins or so. Just for testing. Nothing happens on the device. Then checking the log and do see 1 or 2 commands listed.
Would an ADB log help here as well?
Will also reach out to the community.
Thanks

**Comment by vbier** [comment]
Closed due to inactivity.
