### ISSUE TITLE
habpanelviewer crashes every few days

### ISSUE THREAD

**Issue by sjcliffe** [vbier/habpanelviewer#71]
Hi, 

I've been running habpanelviewer for a couple of years on two oldish (Android 7.1) Lenovo 8" tablets. A earlier this year I upgraded to OH3 and am running the 0.9.27pre app-debug.apk version of habpanelviewer and see the same behaviour. 

Thinking it might be my old tablets I upgraded one to a current version of the Lenovo M8 running Android 10 but am experiencing the same issue. 

I finally got around to getting some abd output and have attached the last 15 minutes worth before it crashed. Hopefully this will show enough to help identify the problem but I have a couple of days worth of logs if you need more. 

[adb.txt.zip](https://github.com/vbier/habpanelviewer/files/7265096/adb.txt.zip)

**Comment by vbier** [comment]
There is not a single HPV message in your log. This doesn't help to find the cause. But most likely it is the HW acceleration of the webview widget. Disable it in the HPV preferences and see if crashes are gone.

**Comment by sjcliffe** [comment]
Hardware acceleration was disabled. 

I've enabled "Log browser messages" to see if this provides some more useful information.

**Comment by sjcliffe** [comment]
I've attached another log. It seems that HPV dies around 14:00:07 in the log:

> 10-05 14:00:07.621  1149  1248 W InputDispatcher: channel '4b6ab22 de.vier_bier.habpanelviewer/de.vier_bier.habpanelviewer.EmptyActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
> 10-05 14:00:07.621  1149  1248 E InputDispatcher: channel '4b6ab22 de.vier_bier.habpanelviewer/de.vier_bier.habpanelviewer.EmptyActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
> 10-05 14:00:07.635  1149  1248 W InputDispatcher: channel 'e1d7baa de.vier_bier.habpanelviewer/de.vier_bier.habpanelviewer.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
> 10-05 14:00:07.636  1149  1248 E InputDispatcher: channel 'e1d7baa de.vier_bier.habpanelviewer/de.vier_bier.habpanelviewer.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
> 10-05 14:00:07.658  1149 17534 I ActivityManager: Process de.vier_bier.habpanelviewer (pid 14120) has died
[adb2.txt.zip](https://github.com/vbier/habpanelviewer/files/7291547/adb2.txt.zip)

**Comment by sjcliffe** [comment]
I was actually not using it when it crashed (it's never crashed when I'm using it). I went out about 15 minutes before it crashed and as part of my OH setup it turns off the screen on the tablet when I'm not home (SCREEN_DIM command at 13:43:31 in the log). 

No other commands were sent after this and there's nothing in the OH logs apart from regular item updates. 

I don't use HPV notifications and my panel layout is pretty simple:
![Screen Shot 2021-10-09 at 17 41 54](https://user-images.githubusercontent.com/6353893/136647276-9b65a354-879d-4438-a5a7-e24474ea932a.png)

**Comment by vbier** [comment]
SCREEN_DIM hides the webview, so it should not matter how your panel layout is. Are you sure you disabled all energy saving mechanisms on your device? There is no exception in the log, so HPV does not seem to crash.
