### ISSUE TITLE
Openhab item state is always null

### ISSUE THREAD

**Issue by s-simma** [vbier/habpanelviewer#8]
Thank's for this nice app.

Downloaded it from Play Store and it runs without problems.

The problem i have is, that the openHAB item state (a contact sensor) which i want to use for activating the display (Samsung Galaxy TAB3 lite) shows allways "null" in the "status information" of the HABPanel viewer (Inside HABPanel the status is shown as ON/OFF or OPEN/CLOSED) -> depending on the map-file.

Bildschirm Steuerung
aktiviert
BewegungGang_EG=null

Android: 4.4.4
HABPanel Viewer: 0.9.13
openHAB: snapshot 2.3.0

**Comment by vbier** [comment]
Are the other openHAB items shown correctly or do you have null for all items? Is the item name correct? Which color has the item name in the preferences?

**Comment by s-simma** [comment]
Hi,
All openHAB items are shown correctly in the dashboard.
The item name is in white color (not red)

http://192.168.1.10:8080/rest/items/BewegungGang_EG/state
OPEN

I have changed the "screen control item" to others. But all of them show "null"
My regx expression is simply: OPEN (is this correct?)

**Comment by vbier** [comment]
Can you post your item definition? I will try to reproduce this evening.

**Comment by s-simma** [comment]
many thank's for your help,

Item definition:
Contact BewegungGang_EG           	"Bewegung Gang-EG [%s]"

and a simple rule:
rule "test1"
    when
        Item LichtEGGang changed
    then
        if (LichtEGGang.state == ON) {
			BewegungGang_EG.sendCommand(OPEN)
		} else {
			BewegungGang_EG.sendCommand(CLOSED)
		}
end

LichtEGGang is a simple switch.

**Comment by vbier** [comment]
I tried to reproduce, but failed. It works as expected with the same item definition on my machine. Can you please download the apk from github, install that, start the app and attach the adb log to this issue?

**Comment by s-simma** [comment]
installed app-debug.apk from github as you suggested.
v0.9.9pre
and everything is ok.

for me strange github version is 0.9.9 and the version in the store is 0.9.13.

thank's for help.

**Comment by s-simma** [comment]
went back to the play store version
v0.9.13
and everything is ok.
The problem is only when using "search server with https:" and ignore certificate message after that.
if i use "search server without https" openhab items reflect the correct state in both versions.

**Comment by vbier** [comment]
Using http instead of https does not really fix the bug. Can you describe in more detail how to reproduce this?
Like
1. start app
2. server is found / not found
3. agree to add security exception
4. configure item
5. leave settings
6. open status info
=> item is null

**Comment by vbier** [comment]
Looks like I found the problem. Adding a certificate exception did not trigger a reconnect of the SSE connection, so the SSE connection still got cert errors and could not update the update the values.

I have updated the apk on github, can you check whether your problem is fixed?

**Comment by s-simma** [comment]
installed your latest app.
with http://
search server
-> item shows the correct state

with https://
search server -> ignore certificate
i get only a black page (for me ok, as i don't have installed a certificate)

if i change from https (black page) to http, i have to restart the program to show the correct state again

for me the problem is fixed.

**Comment by vbier** [comment]
openHAB generates a self-signed certificate on the first start, so you should have a certificate and should be able to access the openHAB webserver at https://192.168.1.10:8443

Does that work in your browser?

**Comment by vbier** [comment]
Can you see the page in the browser? Can you please attach the log containing the https connection?

**Comment by s-simma** [comment]
SSl Zertifikat Ungültig!

Das SSL Zertifikat vonhttps://192.168.1.10 ist nicht
vertrauenswürdig

Ausgestellt
von:C=None,L=None,O=None,CN=openhab.org
Ausgestellt
von:C=None,L=None,O=None,CN=openhab.org
Gültig von:29.06.2017
Gültig bis:27.07.2027

Wollen Sie fortfahren und eine Ausnahme für dieses
Zerifikat speichern?

ABBRECHEN OK

-> OK

**Comment by vbier** [comment]
Not what you get in HabPanelViewer, but in a normal browser like chrome or firefox.

**Comment by s-simma** [comment]
Again, thank you very much for your help.

Using "HABpanel viewer" with http works great. For me this is what i need as i'm inside a VPN.

If i use chrome/firefox with http/https everything is ok (deshboard and item state)
Only the item state is always null if i use "HABpanel viewer" and https connection.

But as you can't reproduce this, we should close this item. 

p.s
Your app helped me a lot to make live with my wife easier.

**Comment by bd8392** [comment]
I have the same problem on Version 0.9.26...motion is detected, but not reported to the item (downloaded from f-droid)
